"""
Django settings for PROJECT project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from easy_thumbnails.conf import Settings as thumbnail_settings



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-i^4$7l#3bks(o8j7(1kk!cs!n%$6%^e_1eb2(_3-39w^qh5lmx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['eventinz.com','www.eventinz.com']


# Application definition

INSTALLED_APPS = [
    'django_crontab',
    'django_admin_geomap',
    'admin_totals',

    # 'jazzmin',
    # 'grappelli',
    # "semantic_admin",
    # "admin_refresh",
    # 'jet',
    # 'admin_tools',
    # 'admin_tools.theming',
    # 'admin_tools.menu',
    # 'admin_tools.dashboard',

    # "semantic_admin",
    # 'jet',
    'jazzmin',
    # 'admin_numeric_filter',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'import_export',
    # 'blogs.apps.BlogsConfig',
    # 'easy_thumbnails',
    # 'image_cropping',
    'django_filters',

    'helloworld',
    'tinymce',
    'vendor_admin',
    'vendor_home',
    # 'vendor_home_french',
    'mathfilters',
    'base',
    'social_django',
    'oauth_app',
    'user_dashboard',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'captcha',
    'django.forms',
    'content_app',
    'eventmanager',
    'indexCMS',
    'vendor_package_manager',
    'chat',
    'blogs',
    'vendor_CMS',
    'vendor_wallet',
    'qr_code',
    'transaction_records_user',
    'about',
    'Eventinz_Terms_And_Conditions',
    'Mails',

    'eventinz_contact_details',
    'Language_Control',
    # 'rangefilter'
    'corsheaders',


    
    
    # 'channels'
]

CORS_ORIGIN_ALLOW_ALL = True

CAPTCHA_IMAGE_SIZE=(200,50)
CAPTCHA_FONT_SIZE=40
CAPTCHA_TIMEOUT = 30
PAYPAL_RECEIVER_EMAIL = 'rownakmazumder@gmail.com'
PAYPAL_TEST = True
SERVE_QR_CODE_IMAGE_PATH = 'qr-code-image/'
TINYMCE_DEFAULT_CONFIG = {
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap print preview anchor searchreplace visualblocks code "
    "fullscreen insertdatetime media table paste code help wordcount spellchecker",
    "toolbar": "undo redo | bold italic underline strikethrough | fontselect fontsizeselect formatselect | alignleft "
    "aligncenter alignright alignjustify | outdent indent |  numlist bullist checklist | forecolor "
    "backcolor casechange permanentpen formatpainter removeformat | pagebreak | charmap emoticons | "
    "fullscreen  preview save print | insertfile image media pageembed template link anchor codesample | "
    "a11ycheck ltr rtl | showcomments addcomment code",
    "custom_undo_redo_levels": 10,
    "language": "en_US",  # To force a specific language instead of the Django current language.
}
TINYMCE_FILEBROWSER=True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',
]
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS
# JAZZMIN_SETTINGS = {
#     # title of the window (Will default to current_admin_site.site_title if absent or None)
#     "site_title": "Eventiz",

#     # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#     "site_header": "Eventiz",

#     # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
#     "site_brand": "Eventiz",

#     # Logo to use for your site, must be present in static files, used for brand on top left
#     "site_logo": "comingsoon/images/EVZ2.png",

#     # CSS classes that are applied to the logo above
#     "site_logo_classes": "",

#     # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
#     "site_icon": None,

#     # Welcome text on the login screen
#     "welcome_sign": "Eventinz Administration",

#     # Copyright on the footer
#     "copyright": "Eventinz.com",
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#     },
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-chevron-right",
#     "changeform_format": "carousel",
#     # override change forms on a per modeladmin basis
#     "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
#     # Add a language dropdown into the admin
    
# }
JAZZMIN_SETTINGS = {
    "site_title": "Eventinz",
    "site_header": "Eventinz",
    "site_brand": "Eventinz",
    "site_icon": "comingsoon/images/EVZ2.png",
    "site_logo": "comingsoon/images/EVZ2.png",
    # Add your own branding here
    
    "welcome_sign": "Welcome to Eventinz",
    # Copyright on the footer
    "copyright": "Eventinz",
    "user_avatar": None,
    ############
    # Top Menu #
    ############
    # Links to put along the top menu
    # "topmenu_links": [
    #     # Url that gets reversed (Permissions can be added)
    #     {"name": "Terms & Conditions", "model": "Eventinz_Terms_And_Conditions.Eventinz_Terms","url":"Terms&Conditions"},
    #     # model admin to link to (Permissions checked against model)
        
    # ],
    #############
    # Side Menu #
    #############
    # Whether to display the side menu
    "welcome_sign": "Eventinz Administration",
    "show_sidebar": True,
    # Whether to aut expand the menu
    "navigation_expanded": True,
    "order_with_respect_to": ["auth", "about","blogs","content_app","eventmanager"],
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "users.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-file",
        "blogs": "fas fa-blog",
        "blogs.blog_category" : "fas fa-rss",
        "blogs.Blog_CMS" : "fas fa-tasks",
        "blogs.Blog_Category_Details": "fas fa-info",
        "blogs.Post" : "fas fa-blog",

        "content_app.event_categories": "fas fa-calendar-week",
        "content_app.event_sub_categories": "fas fa-calendar-week",
        "content_app.Venue_Details" : "fas fa-info",
        "content_app.Our_Vendor_CMS" : "far fa-file",
        "content_app.Venue_Type" : "far fa-sticky-note",

        "eventmanager.create_event_packages" : "fas fa-cube",
        "eventmanager.event_planner_CMS" : "fas fa-file",
        "eventmanager.event_budget_settings" : "fas fa-money-check-alt",
        "eventmanager.event_entries" : "fas fa-plus",
        "eventmanager.event_heads_manager": "fas fa-list-ul"

        
    },
    # # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-right",
    "default_icon_children": "fas fa-chevron-right",
    #################
    # Related Modal #
    #################
    # Use modals instead of popups
    "related_modal_active": False,
    #############
    # UI Tweaks #
    #############
    # Relative paths to custom CSS/JS scripts (must be present in static files)
    # Uncomment this line once you create the bootstrap-dark.css file
    # "custom_css": "css/bootstrap-dark.css",
    "custom_js": None,
    # Whether to show the UI customizer on the sidebar
    "show_ui_builder": True,
    ###############
    # Change view #
    ###############
    "changeform_format": "horizontal_tabs",
    # override change forms on a per modeladmin basis
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": True,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success"
    },
    "actions_sticky_top": False
}

ROOT_URLCONF = 'PROJECT.urls'


STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'social_django.context_processors.backends',  # <-- Here
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'PROJECT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'postgres',
	"HOST" : 'ls-cbbf6d51272f715a15892d95ad5bb4c3cd334e4d.cntan4syrk0k.us-east-1.rds.amazonaws.com',
	'PORT' : '5432',
	'USER' : 'dbmasteruser',
	'PASSWORD' : 'vD%ziijMTgKR=!1!`c0jr*<di3CDQiV['

    }
}
JET_THEMES = [
    {
        'theme': 'default', # theme folder name
        'color': '#47bac1', # color of the theme's button in user menu
        'title': 'Default' # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]
JET_SIDE_MENU_COMPACT = True
JET_CHANGE_FORM_SIBLING_LINKS = True
JET_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultIndexDashboard'

JET_APP_INDEX_DASHBOARD = 'jet.dashboard.dashboard.DefaultAppIndexDashboard'


X_FRAME_OPTIONS = 'SAMEORIGIN'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.zoho.com'
EMAIL_HOST = 'smtp.zeptomail.com'

EMAIL_USE_TLS = True
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@eventinz.com'
# EMAIL_HOST_PASSWORD = 'Rownak@10'
EMAIL_HOST_PASSWORD = 'wSsVR60irEL5X64vzjD8Iew9ylQGAlKnR0p03wajuXT4SvHF9sc8kE3JBFShGKNJGWFpFzFBpO16y00G12BajY4uzFBSXCiF9mqRe1U4J3x17qnvhDzPWmVfkxCMKYgBwwVimWBmG8tu'

# Password validation 
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = True
AUTH_PASSWORD_VALIDATORS = [ {

        'NAME': 
        'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Porto-Novo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'social_core.backends.facebook.FacebookOAuth2',
    'social_core.backends.google.GoogleOAuth2',

    'social_core.backends.twitter.TwitterOAuth',
    'social_core.backends.github.GithubOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',

]
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    },
    'facebook': {
        'METHOD': 'oauth2',
        'SDK_URL': '//connect.facebook.net/{locale}/sdk.js',
        'SCOPE': ['email', 'public_profile'],
        'AUTH_PARAMS': {'auth_type': 'reauthenticate'},
        'INIT_PARAMS': {'cookie': True},
        'FIELDS': [
            'id',
            'first_name',
            'last_name',
            'middle_name',
            'name',
            'name_format',
            'picture',
            'short_name'
        ],
        'EXCHANGE_TOKEN': True,
        'LOCALE_FUNC': 'path.to.callable',
        'VERIFIED_EMAIL': False,
        'VERSION': 'v13.0',
    }
    # 'facebook':{
    #     'SCOPE':[

    #     ]
    # }
}
SITE_ID = 2

# LOGIN_REDIRECT_URL = 'google_auth_success'
# LOGOUT_REDIRECT_URL = 'google_auth_logout'
# LOGIN_URL = 'login'
# LOGOUT_URL = 'logout'
# LOGIN_REDIRECT_URL = 'home'
SOCIAL_AUTH_GOOGLE_KEY = 'ba5e9414a8222a152d9a'
SOCIAL_AUTH_GOOGLE_SECRET = 'e2ac3f9a818dc8082cebbd67800c05f8206bf277' 

SOCIAL_AUTH_FACEBOOK_KEY='429226305282959'
SOCIAL_AUTH_FACEBOOK_SECRET='81be77b92e396afc8181c957833f0e75'

import os
# # import logging
# APP_LOG_FILENAME=os.path.join(BASE_DIR,'log/app.log')
# ERROR_LOG_FILENAME = os.path.join(BASE_DIR,'log/error.log')
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters':{
#         'console':{
#             'format':'%(name)-12s %(levelname)-8s %(message)s'
#         },
#         'file':{
#             'format':'%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
#         }
#     },
#     'handlers': {
#         'console': {
            
#             'class': 'logging.StreamHandler',
#             'formatter':'console'
#         },
#         'file':{
#             'level': 'DEBUG',
#             'class': 'logging.FileHandler',
#             'formatter':'file',
#             'filename':APP_LOG_FILENAME
#         }
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'WARNING',
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console'],
#             'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
#             'propagate': False,
#         },
#     },
# }



RECAPTCHA_PRIVATE_KEY=''
RECAPTCHA_PUBLIC_KEY=''
