# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Language_Control', '0006_alter_language_control_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language_control',
            options={'verbose_name_plural': 'Language Control'},
        ),
        migrations.AlterField(
            model_name='language_control',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=40),
        ),
    ]
