# Generated by Django 4.1 on 2022-10-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Language_Control', '0010_alter_language_control_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language_control',
            name='status',
            field=models.CharField(choices=[('Disable', 'Disable'), ('Enable', 'Enable')], default='Disable', max_length=40),
        ),
    ]
