# Generated by Django 3.2.12 on 2022-06-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=40)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=90)),
                ('Event_Categories', models.CharField(max_length=100)),
                ('Event_Sub_Categories', models.CharField(max_length=200)),
                ('Heads', models.CharField(max_length=30)),
                ('DOE', models.DateField()),
                ('Budget', models.CharField(max_length=300)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=300)),
                ('MCode', models.CharField(max_length=200)),
                ('Mobile', models.CharField(max_length=200)),
                ('Event_Desc', models.TextField()),
                ('status', models.CharField(default='draft', max_length=30)),
                ('user_type', models.CharField(max_length=30)),
            ],
        ),
    ]
