# Generated by Django 3.2.12 on 2022-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_budget_settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimum_Value', models.IntegerField()),
                ('Maximum_Value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='event_heads_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Minimum_Value', models.IntegerField()),
                ('Maximum_Value', models.IntegerField()),
            ],
        ),
    ]
