# Generated by Django 3.2.12 on 2022-07-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_event_budget_settings_event_heads_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_planner_CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='event_planner_cms/images/')),
                ('heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
            ],
        ),
    ]
