# Generated by Django 3.2.12 on 2022-07-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0115_alter_vendor_gallery_photo_id'),
        ('eventmanager', '0003_event_planner_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_budget_settings',
            name='country',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.countries'),
            preserve_default=False,
        ),
    ]
