# Generated by Django 3.2.12 on 2022-07-22 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0116_alter_vendor_gallery_photo_id'),
        ('eventmanager', '0004_event_budget_settings_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='create_event_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premium_amount', models.IntegerField()),
                ('freemium_features', models.TextField()),
                ('premium_features', models.TextField()),
                ('currency_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.countries')),
            ],
        ),
    ]
