# Generated by Django 3.2.12 on 2022-07-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0117_alter_vendor_gallery_photo_id'),
        ('eventmanager', '0005_create_event_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_entries',
            name='package_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_entries',
            name='vendor_type',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_entries',
            name='Budget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.event_budget_settings'),
        ),
    ]
