# Generated by Django 3.2.12 on 2022-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0006_auto_20220723_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_entries',
            name='vendor_type',
            field=models.CharField(max_length=400),
        ),
    ]
