# Generated by Django 3.2.12 on 2022-07-23 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0007_alter_event_entries_vendor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_entries',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
