# Generated by Django 3.2.12 on 2022-07-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0008_event_entries_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_entries',
            name='ev_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
