# Generated by Django 4.1 on 2022-08-23 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0176_alter_vendor_gallery_photo_id'),
        ('eventmanager', '0009_event_entries_ev_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_event_proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('total_amount', models.CharField(max_length=300)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.event_entries')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
        migrations.CreateModel(
            name='vendor_event_proposal_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('rate', models.CharField(max_length=4000)),
                ('proposal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.vendor_event_proposal')),
            ],
        ),
    ]
