# Generated by Django 4.1 on 2022-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0012_alter_event_entries_vendor_type_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_entries',
            name='vendor_type_json',
            field=models.JSONField(default=dict),
        ),
    ]
