# Generated by Django 4.1 on 2022-08-25 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0015_rename_vendor_type_json_event_entries_vendorjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_event_proposal',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
