# Generated by Django 4.1 on 2022-08-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0016_vendor_event_proposal_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_event_proposal_items',
            name='qty',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_event_proposal_items',
            name='total',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_event_proposal_items',
            name='unit',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
