# Generated by Django 4.1 on 2022-09-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0017_vendor_event_proposal_items_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_event_proposal',
            name='status',
            field=models.CharField(default='NA', max_length=4000),
        ),
    ]
