# Generated by Django 4.1 on 2022-09-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0019_vendor_event_proposal_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_event_proposal',
            name='grand_total',
            field=models.CharField(default='0', max_length=4000),
        ),
        migrations.AlterField(
            model_name='vendor_event_proposal',
            name='state_tax',
            field=models.CharField(default='0', max_length=4000),
        ),
    ]
