# Generated by Django 4.1 on 2022-09-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_user_login_aboutme'),
        ('eventmanager', '0020_alter_vendor_event_proposal_grand_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_reviews_vendor_to_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_star', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.event_entries')),
                ('review_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.user_login')),
            ],
        ),
        migrations.CreateModel(
            name='event_reviews_user_to_vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('review_star', models.IntegerField(default=0)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.event_entries')),
                ('review_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.user_login')),
            ],
        ),
    ]
