# Generated by Django 4.1 on 2022-10-05 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0203_alter_vendor_gallery_photo_id_and_more'),
        ('eventmanager', '0024_event_entries_is_archieve'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_reviews_user_to_vendor',
            name='vendor_id',
            field=models.ForeignKey(default=360, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users'),
            preserve_default=False,
        ),
    ]
