# Generated by Django 4.1 on 2022-10-19 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0026_alter_create_event_packages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_entries',
            name='unique_id',
            field=models.TextField(default=0),
        ),
    ]
