# Generated by Django 4.1 on 2022-12-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0028_create_event_packages_premium_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_budget_settings',
            name='Maximum_Value',
            field=models.IntegerField(help_text='Enter 2441139 For Above Minimum Value'),
        ),
    ]
