# Generated by Django 3.2.12 on 2022-05-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_login',
            old_name='Name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='user_login',
            name='city',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='country',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='lname',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='mobile',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='mobile_code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='state',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
