# Generated by Django 3.2.12 on 2022-07-28 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_user_login_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='user_profile_image/'),
            preserve_default=False,
        ),
    ]
