# Generated by Django 4.1 on 2022-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_user_login_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='aboutme',
            field=models.TextField(blank=True),
        ),
    ]
