# Generated by Django 4.1 on 2022-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EV_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_Name', models.CharField(max_length=1000)),
                ('Address_Line_1', models.CharField(max_length=2000)),
                ('Address_Line_2', models.CharField(blank=True, max_length=2000, null=True)),
                ('City', models.CharField(max_length=1000)),
                ('State', models.CharField(max_length=4000)),
                ('Country', models.CharField(max_length=2000)),
                ('Phone_Number', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
