# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventinz_contact_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ev_contact',
            options={'verbose_name_plural': 'Eventinz - Contact Details'},
        ),
    ]
