# Generated by Django 4.1 on 2022-10-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinz_contact_details', '0002_alter_ev_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_contact',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ev_contact',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ev_contact',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ev_contact',
            name='twitter_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
