# Generated by Django 4.1 on 2022-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinz_contact_details', '0003_ev_contact_facebook_url_ev_contact_instagram_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
