# Generated by Django 4.1 on 2022-10-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventinz_contact_details', '0004_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
