# Generated by Django 4.1 on 2022-12-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventinz_contact_details', '0005_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_contact',
            name='contact_page_image',
            field=models.ImageField(default=0, upload_to='contact_details/image/'),
            preserve_default=False,
        ),
    ]
