# Generated by Django 4.1 on 2022-08-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_CMS', '0002_auto_20220615_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_leads_cms_main',
            name='button_text',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
