# Generated by Django 3.2.12 on 2022-04-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=100)),
                ('User_Type', models.CharField(choices=[('Vendor', 'Vendor'), ('User', 'User')], max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header_image')),
                ('Heading', models.CharField(max_length=300)),
            ],
        ),
    ]
