# Generated by Django 3.2.12 on 2022-04-16 04:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='About_text',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
    ]
