# Generated by Django 3.2.12 on 2022-04-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0003_about_about_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entries',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='Name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='entries',
            old_name='Phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='entries',
            name='lname',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
