# Generated by Django 3.2.12 on 2022-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0005_mail_user_mail_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail_user',
            name='subject',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mail_vendor',
            name='subject',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
