# Generated by Django 3.2.12 on 2022-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0006_auto_20220416_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='button_text',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
