# Generated by Django 3.2.12 on 2022-04-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0007_header_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='country',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
