# Generated by Django 4.1 on 2022-08-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0009_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='subscribe_status',
            field=models.CharField(choices=[(0, 'Subscribed'), (1, 'Un-Subscribed')], default=1, max_length=30),
        ),
    ]
