# Generated by Django 4.1 on 2022-08-13 08:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0011_alter_newsletter_subscribe_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Mails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_to', models.CharField(choices=[('Vendors', 'Vendors'), ('Vendors - Registered Group', 'Vendors - Registered Group'), ('Hosts', 'Hosts'), ('Hosts - Registered Group', 'Hosts - Registered Group'), ('Newsletters', 'Newsletter Subscribers')], max_length=4000)),
                ('subject', models.TextField()),
                ('content', tinymce.models.HTMLField()),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
