# Generated by Django 4.1 on 2022-08-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0012_schedule_mails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule_mails',
            name='content',
        ),
    ]
