# Generated by Django 4.1 on 2022-09-13 04:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Welcome_Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_type', models.CharField(choices=[('Hello', 'Hello'), ('Greetings', 'Greetings'), ('Congratulations', 'Congratulations'), ('Welcome', 'Welcome')], max_length=400)),
                ('subject', models.CharField(max_length=4000)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
