# Generated by Django 3.2.12 on 2022-07-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EV_About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Text', models.CharField(max_length=300)),
                ('Header_subtext', models.CharField(max_length=300)),
                ('Header_Background', models.ImageField(upload_to='eventinz_about/')),
                ('Who_We_Are_Heading', models.CharField(max_length=300)),
                ('Who_We_Are_Sub_Heading', models.CharField(max_length=4000)),
                ('Who_We_Are_Image', models.ImageField(upload_to='eventinz_about/Who_We_are')),
                ('Mission_Text', models.CharField(max_length=300)),
                ('Mission_Sub_Text', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Eventinz_Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='ev_teams/profile_pic/')),
                ('Full_Name', models.CharField(max_length=400)),
                ('Designation', models.CharField(max_length=5000)),
                ('linkedin_url', models.URLField()),
            ],
        ),
    ]
