# Generated by Django 4.1 on 2022-08-16 14:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_eventinz_teams_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ev_about',
            name='Who_We_Are_Sub_Heading',
            field=tinymce.models.HTMLField(),
        ),
    ]
