# Generated by Django 4.1 on 2022-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_ev_about_who_we_are_sub_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='ev_about',
            name='Eventinz_Teams_Header',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
