# Generated by Django 4.1 on 2022-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_ev_about_eventinz_teams_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_type',
            field=models.CharField(choices=[('HP', 'HP'), ('Others', 'Others'), ('AWS', 'AWS'), ('LINUX', 'LINUX'), ('IBM', 'IBM')], default=1, max_length=4000),
            preserve_default=False,
        ),
    ]
