# Generated by Django 4.1 on 2022-08-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_remove_eventinz_teams_certification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_link_6',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_link_7',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_link_8',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_logo_6',
            field=models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/'),
        ),
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_logo_7',
            field=models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/'),
        ),
        migrations.AddField(
            model_name='eventinz_teams',
            name='certification_logo_8',
            field=models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/'),
        ),
    ]
