# Generated by Django 4.1 on 2022-10-01 20:45

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_eventinz_teams_certification_link_6_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EV_About_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Text', models.CharField(max_length=300)),
                ('Header_subtext', models.CharField(max_length=300)),
                ('Header_Background', models.ImageField(upload_to='eventinz_about/')),
                ('Who_We_Are_Heading', models.CharField(max_length=300)),
                ('Who_We_Are_Sub_Heading', tinymce.models.HTMLField()),
                ('Who_We_Are_Image', models.ImageField(upload_to='eventinz_about/Who_We_are')),
                ('Mission_Text', models.CharField(max_length=300)),
                ('Mission_Sub_Text', models.CharField(max_length=4000)),
                ('Eventinz_Teams_Header', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Eventinz_Teams_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(upload_to='ev_teams/profile_pic/')),
                ('Full_Name', models.CharField(max_length=400)),
                ('Designation', models.CharField(max_length=5000)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('certification_logo_1', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_1', models.URLField(blank=True, null=True)),
                ('certification_logo_2', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_2', models.URLField(blank=True, null=True)),
                ('certification_logo_3', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_3', models.URLField(blank=True, null=True)),
                ('certification_logo_4', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_4', models.URLField(blank=True, null=True)),
                ('certification_logo_5', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_5', models.URLField(blank=True, null=True)),
                ('certification_logo_6', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_6', models.URLField(blank=True, null=True)),
                ('certification_logo_7', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_7', models.URLField(blank=True, null=True)),
                ('certification_logo_8', models.ImageField(blank=True, null=True, upload_to='ev_teams/profile/user_certification/')),
                ('certification_link_8', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
