# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_ev_about_french_eventinz_teams_french'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ev_about',
            options={'verbose_name_plural': 'Eventinz About'},
        ),
        migrations.AlterModelOptions(
            name='eventinz_teams',
            options={'verbose_name_plural': 'Eventinz Teams'},
        ),
    ]
