# Generated by Django 3.2.12 on 2022-06-19 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_admin', '0081_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_wallet_manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_balance', models.CharField(max_length=400)),
                ('remaining_balance', models.CharField(max_length=400)),
                ('last_recharged_on', models.DateField()),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
