# Generated by Django 3.2.12 on 2022-06-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='how_eventinz_works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Text', models.CharField(max_length=200)),
                ('Sub_Text', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='main_site/how_eventinz_works/bg_image')),
                ('Step_1_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_1_Text', models.CharField(max_length=30)),
                ('Step_2_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_2_Text', models.CharField(max_length=40)),
                ('Step_3_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_3_Text', models.CharField(max_length=40)),
            ],
        ),
    ]
