# Generated by Django 3.2.12 on 2022-06-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0002_how_eventinz_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_heading', models.CharField(max_length=400)),
                ('adv_subtext', models.CharField(max_length=400)),
                ('adv_bg_image', models.ImageField(upload_to='main_site/advertisement/bg')),
                ('adv_image', models.ImageField(upload_to='main_site/advertisement/img')),
            ],
        ),
    ]
