# Generated by Django 3.2.12 on 2022-06-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0003_advertisement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AlterModelOptions(
            name='how_eventinz_works',
            options={'verbose_name_plural': 'How Eventinz Works'},
        ),
    ]
