# Generated by Django 4.1 on 2022-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0004_auto_20220603_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Deals_Index_CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
                ('Package_Button_Text', models.CharField(max_length=300)),
                ('Deals_Button_Text', models.CharField(max_length=400)),
            ],
        ),
    ]
