# Generated by Django 4.1 on 2022-08-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0005_vendor_deals_index_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Categories_Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=400)),
                ('Sub_Heading', models.CharField(max_length=400)),
            ],
        ),
    ]
