# Generated by Django 4.1 on 2022-10-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0006_vendor_categories_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='advertisement_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adv_heading', models.CharField(max_length=400)),
                ('adv_subtext', models.CharField(max_length=400)),
                ('adv_bg_image', models.ImageField(upload_to='main_site/advertisement/bg')),
                ('adv_image', models.ImageField(upload_to='main_site/advertisement/img')),
            ],
            options={
                'verbose_name_plural': 'Advertisements',
            },
        ),
        migrations.CreateModel(
            name='how_eventinz_works_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header_Text', models.CharField(max_length=200)),
                ('Sub_Text', models.CharField(max_length=200)),
                ('background_image', models.ImageField(upload_to='main_site/how_eventinz_works/bg_image')),
                ('Step_1_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_1_Text', models.CharField(max_length=30)),
                ('Step_2_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_2_Text', models.CharField(max_length=40)),
                ('Step_3_Icon', models.ImageField(upload_to='main_site/how_eventinz_works/icons')),
                ('Step_3_Text', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'How Eventinz Works',
            },
        ),
        migrations.CreateModel(
            name='index_headers_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Header', models.CharField(max_length=300)),
                ('sub_header', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Index Headers',
            },
        ),
        migrations.CreateModel(
            name='index_slider_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='main_site/slider/img')),
            ],
            options={
                'verbose_name_plural': 'Index Slider',
            },
        ),
        migrations.CreateModel(
            name='Vendor_Categories_Text_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Heading', models.CharField(max_length=400)),
                ('Sub_Heading', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor_Deals_Index_CMS_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=400)),
                ('sub_heading', models.CharField(max_length=400)),
                ('Package_Button_Text', models.CharField(max_length=300)),
                ('Deals_Button_Text', models.CharField(max_length=400)),
            ],
        ),
    ]
