# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexCMS', '0007_advertisement_french_how_eventinz_works_french_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor_categories_text',
            options={'verbose_name_plural': 'Vendor Categories - Index'},
        ),
        migrations.AlterModelOptions(
            name='vendor_deals_index_cms',
            options={'verbose_name_plural': 'Vendor Deals - Index CMS'},
        ),
    ]
