# Generated by Django 4.1 on 2022-08-18 14:02

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventinz_Privacy_Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='privacy/content/')),
                ('page_header', models.CharField(max_length=1000)),
                ('privacy_policy_text', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='Eventinz_Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_image', models.ImageField(upload_to='tnc/content/')),
                ('page_header', models.CharField(max_length=1000)),
                ('Terms_and_conditon_text', tinymce.models.HTMLField()),
            ],
        ),
    ]
