# Generated by Django 4.1 on 2022-08-18 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventinz_Terms_And_Conditions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinz_privacy_policy',
            old_name='privacy_policy_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='eventinz_terms',
            old_name='Terms_and_conditon_text',
            new_name='content',
        ),
    ]
