# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eventinz_Terms_And_Conditions', '0003_eventinz_privacy_policy_french_eventinz_terms_french'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventinz_privacy_policy',
            options={'verbose_name_plural': 'Eventinz - Privacy Policy'},
        ),
        migrations.AlterModelOptions(
            name='eventinz_terms',
            options={'verbose_name_plural': 'Eventinz - Terms & Conditions'},
        ),
    ]
