# Generated by Django 3.2.12 on 2022-05-31 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0002_event_categories_french_event_sub_categories_french'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event_categories',
            options={'verbose_name_plural': 'Event Categories'},
        ),
        migrations.AlterModelOptions(
            name='event_categories_french',
            options={'verbose_name_plural': 'Event Categories (French)'},
        ),
        migrations.AlterModelOptions(
            name='event_sub_categories',
            options={'verbose_name_plural': 'Event Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='event_sub_categories_french',
            options={'verbose_name_plural': 'Event Sub Categories (French)'},
        ),
        migrations.AlterModelOptions(
            name='index_headers',
            options={'verbose_name_plural': 'Index Headers'},
        ),
        migrations.AlterModelOptions(
            name='index_slider',
            options={'verbose_name_plural': 'Index Slider'},
        ),
        migrations.AlterField(
            model_name='event_sub_categories_french',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.event_categories_french'),
        ),
    ]
