# Generated by Django 3.2.12 on 2022-06-01 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0003_auto_20220531_1709'),
    ]

    operations = [
        migrations.DeleteModel(
            name='index_headers',
        ),
        migrations.DeleteModel(
            name='index_slider',
        ),
    ]
