# Generated by Django 3.2.12 on 2022-06-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0004_auto_20220601_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=300)),
            ],
        ),
    ]
