# Generated by Django 3.2.12 on 2022-06-10 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0005_venue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_subheading', models.CharField(max_length=300)),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.venue_type')),
            ],
        ),
    ]
