# Generated by Django 3.2.12 on 2022-06-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0006_venue_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue_type',
            options={'verbose_name_plural': 'Venue-Event Type'},
        ),
    ]
