# Generated by Django 3.2.12 on 2022-06-10 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0007_alter_venue_type_options'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='venue_details',
        #     name='venue_name',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.venue_type', to_field='venue_name'),
        # ),
        # migrations.AlterField(
        #     model_name='venue_type',
        #     name='venue_name',
        #     field=models.CharField(max_length=300, unique=True),
        # ),
    ]
