# Generated by Django 3.2.12 on 2022-06-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0009_alter_venue_details_venue_name'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='venue_type',
        #     name='venue_name',
        #     field=models.CharField(max_length=300),
        # ),
    ]
