# Generated by Django 3.2.12 on 2022-06-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0010_alter_venue_type_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_Type_by_venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Venue Type',
            },
        ),
    ]
