# Generated by Django 3.2.12 on 2022-06-10 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0011_venue_type_by_venue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue_details',
            options={'verbose_name_plural': 'Venue Details'},
        ),
    ]
