# Generated by Django 3.2.12 on 2022-06-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0012_alter_venue_details_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_details',
            name='venue_image',
            field=models.ImageField(default=0, upload_to='venue_content/image/'),
            preserve_default=False,
        ),
    ]
