# Generated by Django 3.2.12 on 2022-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0013_venue_details_venue_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue_main_home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_head_image', models.ImageField(upload_to='venue_content/main_venue/image/')),
                ('venue_header', models.CharField(max_length=300)),
            ],
        ),
    ]
