# Generated by Django 3.2.12 on 2022-06-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0015_auto_20220611_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue_details',
            name='venue_image',
        ),
        migrations.AddField(
            model_name='venue_type_by_venue',
            name='venue_image',
            field=models.ImageField(default=0, upload_to='venue_content/image/'),
            preserve_default=False,
        ),
    ]
