# Generated by Django 3.2.12 on 2022-06-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0016_auto_20220612_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_details',
            name='venue_image',
            field=models.ImageField(default=0, upload_to='venue_content/image/detailed/'),
            preserve_default=False,
        ),
    ]
