# Generated by Django 3.2.12 on 2022-07-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0024_alter_venue_details_venue_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_categories',
            name='category_img',
            field=models.ImageField(default=0, upload_to='ev_cats/images/'),
            preserve_default=False,
        ),
    ]
