# Generated by Django 3.2.12 on 2022-07-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0025_event_categories_category_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue_type',
            name='img',
            field=models.ImageField(default=0, upload_to='venue_img/imgs/'),
            preserve_default=False,
        ),
    ]
