# Generated by Django 3.2.12 on 2022-08-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0026_venue_type_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange_Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_country', models.CharField(max_length=4000)),
                ('dest_country', models.CharField(max_length=4000)),
                ('ex_rate', models.CharField(max_length=5000)),
            ],
        ),
    ]
