# Generated by Django 3.2.12 on 2022-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0027_exchange_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='cron_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_type', models.CharField(max_length=100)),
                ('cron_purpose', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=300)),
            ],
        ),
    ]
