# Generated by Django 4.1 on 2022-08-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0029_exchange_rates_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Vendor_CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='our_vendor/bg_image/')),
                ('Header_Text', models.CharField(max_length=3000)),
                ('Display_text', models.CharField(max_length=4000)),
            ],
        ),
    ]
