# Generated by Django 4.1 on 2022-10-01 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0030_our_vendor_cms'),
    ]

    operations = [
        migrations.CreateModel(
            name='cron_activities_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cron_type', models.CharField(max_length=100)),
                ('cron_purpose', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Rates_API_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=500)),
                ('apikey', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange_Rates_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_country', models.CharField(max_length=4000)),
                ('dest_country', models.CharField(max_length=4000)),
                ('ex_rate', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Vendor_CMS_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='our_vendor/bg_image/')),
                ('Header_Text', models.CharField(max_length=3000)),
                ('Display_text', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_main_home_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_head_image', models.ImageField(upload_to='venue_content/main_venue/image/')),
                ('venue_header', models.CharField(max_length=300)),
                ('venue_by_venue', models.CharField(max_length=300)),
                ('venue_by_venue_subheading', models.CharField(max_length=300)),
                ('venue_by_event', models.CharField(max_length=300)),
                ('venue_by_event_subheading', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Venue_Type_by_venue_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=100)),
                ('venue_image', models.ImageField(upload_to='venue_content/image/')),
            ],
            options={
                'verbose_name_plural': 'Venue Type',
            },
        ),
        migrations.CreateModel(
            name='Venue_Type_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='venue_img/imgs/')),
            ],
            options={
                'verbose_name_plural': 'Venue-Event Type',
            },
        ),
        migrations.CreateModel(
            name='Venue_Details_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_subheading', models.CharField(max_length=300)),
                ('venue_image', models.ImageField(upload_to='venue_content/image/detailed/')),
                ('venue_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.venue_type')),
            ],
            options={
                'verbose_name_plural': 'Venue Details',
            },
        ),
    ]
