# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0031_cron_activities_french_exchange_rates_api_french_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='our_vendor_cms',
            options={'verbose_name_plural': "'Our Vendor' - Page Header Management"},
        ),
    ]
