# Generated by Django 4.1 on 2022-10-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0032_alter_our_vendor_cms_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue_main_home',
            options={'verbose_name_plural': "'Venue' - Content Management"},
        ),
    ]
