# Generated by Django 3.2.12 on 2022-06-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_admin', '0095_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_transaction_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=4000)),
                ('transaction_type', models.CharField(max_length=400)),
                ('transaction_amount', models.CharField(max_length=300)),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.request_a_quote')),
            ],
        ),
    ]
