# Generated by Django 3.2.12 on 2022-07-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transaction_records',
            name='remarks',
            field=models.CharField(default='1', max_length=300),
        ),
    ]
