# Generated by Django 3.2.12 on 2022-07-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0002_user_transaction_records_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_transaction_records',
            name='email',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
