# Generated by Django 4.1 on 2022-08-19 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_user_login_aboutme'),
        ('vendor_admin', '0167_alter_vendor_gallery_photo_id'),
        ('transaction_records_user', '0003_user_transaction_records_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Payment_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Name', models.CharField(max_length=1000)),
                ('Account_Name', models.CharField(max_length=4000)),
                ('Bank_AC_Number', models.CharField(max_length=4000)),
                ('Country', models.CharField(max_length=1000)),
                ('Bank_Reference_Code', models.CharField(max_length=4000)),
                ('Depositor_Name', models.CharField(max_length=2000)),
                ('Deposited_On', models.DateField()),
                ('Transaction_File_Record', models.FileField(upload_to='transaction_records_user/user_data/')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.user_login')),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_quote_invoice')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.request_a_quote')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
