# Generated by Django 4.1 on 2022-08-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0004_vendor_payment_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_payment_history',
            name='Deposited_On',
        ),
    ]
