# Generated by Django 4.1 on 2022-08-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0005_remove_vendor_payment_history_deposited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history',
            name='Payment_By',
            field=models.CharField(default=0, max_length=4000),
            preserve_default=False,
        ),
    ]
