# Generated by Django 4.1 on 2022-08-21 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0006_vendor_payment_history_payment_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_payment_history',
            name='invoice_id',
        ),
    ]
