# Generated by Django 4.1 on 2022-09-04 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0006_user_login_aboutme'),
        ('vendor_admin', '0185_alter_vendor_gallery_photo_id'),
        ('eventmanager', '0018_vendor_event_proposal_status'),
        ('transaction_records_user', '0007_remove_vendor_payment_history_invoice_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_Payment_History_events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Name', models.CharField(max_length=1000)),
                ('Account_Name', models.CharField(max_length=4000)),
                ('Bank_AC_Number', models.CharField(max_length=4000)),
                ('Country', models.CharField(max_length=1000)),
                ('Bank_Reference_Code', models.CharField(max_length=4000)),
                ('Depositor_Name', models.CharField(max_length=2000)),
                ('Payment_By', models.CharField(max_length=4000)),
                ('Transaction_File_Record', models.FileField(upload_to='transaction_records_user/events/user_data/')),
                ('host_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.user_login')),
                ('quote_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventmanager.event_entries')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
