# Generated by Django 4.1 on 2022-09-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0008_vendor_payment_history_events'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_payment_history_events',
            old_name='quote_id',
            new_name='event_id',
        ),
    ]
