# Generated by Django 4.1 on 2022-09-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0009_rename_quote_id_vendor_payment_history_events_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_payment_history_events',
            name='Bank_Reference_Code',
        ),
        migrations.RemoveField(
            model_name='vendor_payment_history_events',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='vendor_payment_history_events',
            name='Depositor_Name',
        ),
        migrations.RemoveField(
            model_name='vendor_payment_history_events',
            name='Payment_By',
        ),
    ]
