# Generated by Django 4.1 on 2022-09-06 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0010_remove_vendor_payment_history_events_bank_reference_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history_events',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
