# Generated by Django 4.1 on 2022-09-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0011_vendor_payment_history_events_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history_events',
            name='Amount',
            field=models.CharField(default=0, max_length=4000),
            preserve_default=False,
        ),
    ]
