# Generated by Django 4.1 on 2022-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0012_vendor_payment_history_events_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history_events',
            name='status',
            field=models.CharField(default='Pending Verification', max_length=5000),
        ),
    ]
