# Generated by Django 4.1 on 2022-10-08 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0013_vendor_payment_history_events_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
