# Generated by Django 4.1 on 2022-10-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0014_vendor_payment_history_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history',
            name='tran_num',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
