# Generated by Django 4.1 on 2022-10-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0015_vendor_payment_history_tran_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_payment_history',
            name='tran_num',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
