# Generated by Django 4.1 on 2022-10-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0016_alter_vendor_payment_history_tran_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_payment_history',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
