# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_records_user', '0017_vendor_payment_history_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_transaction_records',
            options={'verbose_name_plural': 'User Transaction Records'},
        ),
        migrations.AlterModelOptions(
            name='vendor_payment_history',
            options={'verbose_name_plural': 'Vendor Payment History'},
        ),
        migrations.AlterModelOptions(
            name='vendor_payment_history_events',
            options={'verbose_name_plural': 'Vendor Payment History - Events'},
        ),
    ]
