# Generated by Django 3.2.12 on 2022-06-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='quote_id',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
