# Generated by Django 3.2.12 on 2022-04-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='Profile_Img',
            field=models.ImageField(blank=True, null=True, upload_to='vendors/profile/images'),
        ),
    ]
