# Generated by Django 3.2.12 on 2022-04-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0002_auto_20220429_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='Password',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='User_ID',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
