# Generated by Django 3.2.12 on 2022-04-29 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0003_auto_20220429_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='Alternative_Mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='Company_Address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='Company_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='package',
            field=models.CharField(default='123', max_length=200),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='valid_till',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
