# Generated by Django 3.2.12 on 2022-04-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0006_alter_vendor_users_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_users',
            name='Alternative_Mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
