# Generated by Django 3.2.12 on 2022-04-29 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0007_alter_vendor_users_alternative_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_users',
            name='Company_Address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
