# Generated by Django 3.2.12 on 2022-04-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0008_alter_vendor_users_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_users',
            name='Company_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
