# Generated by Django 3.2.12 on 2022-04-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0011_alter_vendor_users_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_users',
            name='valid_till',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
