# Generated by Django 3.2.12 on 2022-05-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0013_vendor_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=300)),
                ('package_description', models.CharField(max_length=200)),
                ('package_fee', models.IntegerField()),
                ('service_fee', models.IntegerField()),
                ('payment_by', models.CharField(max_length=300)),
                ('time', models.CharField(max_length=300)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('Valid_to', models.DateTimeField()),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_id', models.CharField(max_length=400)),
                ('Vendor_name', models.CharField(max_length=200)),
                ('Vendor_company_name', models.CharField(max_length=300)),
                ('vendor_phone', models.IntegerField()),
                ('vendor_email', models.EmailField(max_length=254)),
                ('purchase_type', models.CharField(max_length=300)),
            ],
        ),
    ]
