# Generated by Django 3.2.12 on 2022-05-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0016_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='capital',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='currency',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='latitude',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='longitude',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='phone_code',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countries',
            name='region',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
