# Generated by Django 3.2.12 on 2022-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0019_auto_20220503_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='country',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='state',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
