# Generated by Django 3.2.12 on 2022-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0020_auto_20220503_0706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_users',
            old_name='country',
            new_name='country_code',
        ),
        migrations.RenameField(
            model_name='vendor_users',
            old_name='state',
            new_name='country_name',
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='state_code',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='state_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
