# Generated by Django 3.2.12 on 2022-05-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0023_auto_20220503_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_subscription',
            name='package_fee',
            field=models.IntegerField(blank=True, default=123),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='service_fee',
            field=models.IntegerField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='vendor_phone',
            field=models.IntegerField(blank=True, default=123),
        ),
    ]
