# Generated by Django 3.2.12 on 2022-05-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0025_alter_vendor_subscription_valid_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_subscription',
            name='status',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
