# Generated by Django 3.2.12 on 2022-05-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0027_vendor_subscription_country_cuurency'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('Jan_sales', models.IntegerField(default=0)),
                ('Feb_sales', models.IntegerField(default=0)),
                ('Mar_sales', models.IntegerField(default=0)),
                ('Apr_sales', models.IntegerField(default=0)),
                ('May_sales', models.IntegerField(default=0)),
                ('Jun_sales', models.IntegerField(default=0)),
                ('Jul_sales', models.IntegerField(default=0)),
                ('Aug_sales', models.IntegerField(default=0)),
                ('Sep_sales', models.IntegerField(default=0)),
                ('Oct_sales', models.IntegerField(default=0)),
                ('Nov_sales', models.IntegerField(default=0)),
                ('Dec_sales', models.IntegerField(default=0)),
            ],
        ),
    ]
