# Generated by Django 3.2.12 on 2022-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0028_total_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_accepted_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=300)),
                ('order_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='total_earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('Jan_earnings', models.IntegerField(default=0)),
                ('Feb_earnings', models.IntegerField(default=0)),
                ('Mar_earnings', models.IntegerField(default=0)),
                ('Apr_earnings', models.IntegerField(default=0)),
                ('May_earnings', models.IntegerField(default=0)),
                ('Jun_earnings', models.IntegerField(default=0)),
                ('Jul_earnings', models.IntegerField(default=0)),
                ('Aug_earnings', models.IntegerField(default=0)),
                ('Sep_earnings', models.IntegerField(default=0)),
                ('Oct_earnings', models.IntegerField(default=0)),
                ('Nov_earnings', models.IntegerField(default=0)),
                ('Dec_earnings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='total_earnings_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='total_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('order_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='total_rejected_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=300)),
                ('order_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='total_sales_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.CharField(max_length=30)),
                ('total_count', models.IntegerField(default=0)),
            ],
        ),
    ]
