# Generated by Django 3.2.12 on 2022-05-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0029_total_accepted_orders_total_earnings_total_earnings_count_total_orders_total_rejected_orders_total_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_subscription',
            name='is_enterprise_vendor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
