# Generated by Django 3.2.12 on 2022-05-08 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0030_vendor_subscription_is_enterprise_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_subscription',
            name='is_enterprise_vendor',
        ),
        migrations.AddField(
            model_name='vendor_packages',
            name='is_enterprise_vendor',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
