# Generated by Django 3.2.12 on 2022-05-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0031_auto_20220508_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_packages',
            name='price',
        ),
        migrations.AddField(
            model_name='vendor_packages',
            name='price_biannual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor_packages',
            name='price_quarter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor_packages',
            name='price_yearly',
            field=models.IntegerField(default=0),
        ),
    ]
