# Generated by Django 3.2.12 on 2022-05-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0032_auto_20220508_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_packages',
            old_name='price_yearly',
            new_name='price',
        ),
    ]
