# Generated by Django 3.2.12 on 2022-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0033_rename_price_yearly_vendor_packages_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=400)),
            ],
        ),
    ]
