# Generated by Django 3.2.12 on 2022-05-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0035_vendor_subscription_vendor_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_subscription',
            name='Valid_to',
            field=models.DateTimeField(blank=True),
        ),
    ]
