# Generated by Django 3.2.12 on 2022-05-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0036_alter_vendor_subscription_valid_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_subscription',
            name='valid_from',
            field=models.DateTimeField(blank=True),
        ),
    ]
