# Generated by Django 3.2.12 on 2022-05-09 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0037_alter_vendor_subscription_valid_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_subscription',
            old_name='Valid_to',
            new_name='valid_to',
        ),
    ]
