# Generated by Django 3.2.12 on 2022-05-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0042_choicelist_samplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_categories',
            name='category_cover_image',
            field=models.ImageField(default=0, upload_to='vendors/bg/categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_categories',
            name='category_icon',
            field=models.ImageField(default=0, upload_to='vendors/icons/categories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_categories_french',
            name='category_cover_image',
            field=models.ImageField(default=0, upload_to='vendors/bg/categories_french'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_categories_french',
            name='category_icon',
            field=models.ImageField(default=0, upload_to='vendors/icons/categories_french'),
            preserve_default=False,
        ),
    ]
