# Generated by Django 3.2.12 on 2022-05-27 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0044_vendor_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_sub_categories_french',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=200)),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories_french')),
            ],
        ),
    ]
