# Generated by Django 3.2.12 on 2022-05-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0045_vendor_sub_categories_french'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency_model',
            options={'verbose_name_plural': 'Currency'},
        ),
        migrations.AlterModelOptions(
            name='states',
            options={'verbose_name_plural': 'States'},
        ),
        migrations.AlterModelOptions(
            name='total_accepted_orders',
            options={'verbose_name_plural': 'Total Accepted Orders'},
        ),
        migrations.AlterModelOptions(
            name='total_earnings',
            options={'verbose_name_plural': 'Total Earnings'},
        ),
        migrations.AlterModelOptions(
            name='total_earnings_count',
            options={'verbose_name_plural': 'Total Earnings Count'},
        ),
        migrations.AlterModelOptions(
            name='total_orders',
            options={'verbose_name_plural': 'Total Orders'},
        ),
        migrations.AlterModelOptions(
            name='total_rejected_orders',
            options={'verbose_name_plural': 'Total Rejected Orders'},
        ),
        migrations.AlterModelOptions(
            name='total_sales',
            options={'verbose_name_plural': 'Total Sales'},
        ),
        migrations.AlterModelOptions(
            name='total_sales_count',
            options={'verbose_name_plural': 'Total Sales Count'},
        ),
        migrations.AlterModelOptions(
            name='vendor_categories',
            options={'verbose_name_plural': 'Vendor Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendor_categories_french',
            options={'verbose_name_plural': 'Vendor Categories (French)'},
        ),
        migrations.AlterModelOptions(
            name='vendor_packages',
            options={'verbose_name_plural': 'Vendor Packages'},
        ),
        migrations.AlterModelOptions(
            name='vendor_sub_categories',
            options={'verbose_name_plural': 'Vendor Sub Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendor_sub_categories_french',
            options={'verbose_name_plural': 'Vendor Sub Categories (French)'},
        ),
        migrations.AlterModelOptions(
            name='vendor_subscription',
            options={'verbose_name_plural': 'Vendor Subscription'},
        ),
        migrations.AlterModelOptions(
            name='vendor_users',
            options={'verbose_name_plural': 'Vendor Profile'},
        ),
    ]
