# Generated by Django 3.2.12 on 2022-06-12 06:52

from django.db import migrations, models
import django.db.models.deletion
# import jsonfield.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0017_venue_details_venue_image'),
        ('vendor_admin', '0047_message_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Listing_name', models.CharField(max_length=300)),
                ('Max_Budget', models.IntegerField()),
                ('Min_Budget', models.IntegerField()),
                ('Description', tinymce.models.HTMLField()),
                ('feature_sets', models.JSONField(default=dict)),
                ('Listing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.event_categories')),
            ],
        ),
    ]
