# Generated by Django 3.2.12 on 2022-06-12 06:54

from django.db import migrations,models
# import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0048_listings_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings_data',
            name='capacity_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listings_data',
            name='caterer_sets',
            field=models.JSONField(default=dict),
        ),
    ]
