# Generated by Django 3.2.12 on 2022-06-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0049_auto_20220612_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings_data',
            name='vendor_id',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
