# Generated by Django 3.2.12 on 2022-06-12 07:27

from django.db import migrations,models
# import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0050_listings_data_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings_data',
            name='DnR',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listings_data',
            name='atmosphere_sets',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listings_data',
            name='event_planner_sets',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listings_data',
            name='photo_vdo_sets',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='listings_data',
            name='speciality_sets',
            field=models.JSONField(default=dict),
        ),
    ]
