# Generated by Django 3.2.12 on 2022-06-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0017_venue_details_venue_image'),
        ('vendor_admin', '0051_auto_20220612_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question_Icon', models.ImageField(upload_to='main_site/vendor/question_category/images/')),
                ('Question_Text', models.CharField(help_text='Keep it short and simple', max_length=300)),
                ('Question_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_app.event_categories')),
            ],
        ),
    ]
