# Generated by Django 3.2.12 on 2022-06-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0052_vendor_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_question_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=300)),
            ],
        ),
    ]
