# Generated by Django 3.2.12 on 2022-06-12 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0053_vendor_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_questions',
            name='Question_Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_question_type'),
            preserve_default=False,
        ),
    ]
