# Generated by Django 3.2.12 on 2022-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0054_vendor_questions_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='max_budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='min_budget',
            field=models.IntegerField(default=0),
        ),
    ]
