# Generated by Django 3.2.12 on 2022-06-13 10:31

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0055_auto_20220612_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_public_packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('what_included', tinymce.models.HTMLField()),
                ('package_price', models.IntegerField()),
                ('package_category', models.CharField(max_length=300)),
                ('package_for', models.CharField(max_length=300)),
                ('valid_till', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.CharField(max_length=300)),
            ],
        ),
    ]
