# Generated by Django 3.2.12 on 2022-06-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0056_vendor_public_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='vendor_name',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
