# Generated by Django 3.2.12 on 2022-06-13 15:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0060_alter_vendor_users_event_category_serve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_users',
            name='event_category_serve',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='{"":""}'),
        ),
    ]
