# Generated by Django 3.2.12 on 2022-06-13 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0061_alter_vendor_users_event_category_serve'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='category_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
