# Generated by Django 3.2.12 on 2022-06-13 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0062_vendor_public_packages_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_src', models.ImageField(upload_to='main_site/vendor_photos/uploads/')),
                ('photo_category', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=300)),
                ('photo_id', models.CharField(default=uuid.UUID('eb08f78b-427b-4cf7-a3e6-4a5c8cb93617'), max_length=300)),
            ],
        ),
    ]
