# Generated by Django 3.2.12 on 2022-06-13 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0063_vendor_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_gallery',
            name='vendor_email',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c3804e4a-805d-4bad-83ac-56e0286aacb9'), max_length=300),
        ),
    ]
