# Generated by Django 3.2.12 on 2022-06-14 16:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0064_auto_20220613_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('b2faae08-cc50-4f47-b930-6266514fbaa5'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='event_category_serve',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
