# Generated by Django 3.2.12 on 2022-06-14 19:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0065_auto_20220614_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_questions',
            name='Question_Category',
        ),
        migrations.RemoveField(
            model_name='vendor_questions',
            name='Question_Type',
        ),
        migrations.AddField(
            model_name='vendor_questions',
            name='Question_display_text',
            field=models.CharField(default=0, max_length=300),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='question_field',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('03e14723-a0ec-4a23-9569-3dedbcf87688'), max_length=300),
        ),
    ]
