# Generated by Django 3.2.12 on 2022-06-15 05:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0067_auto_20220614_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='caterer_field',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('7af99262-9466-464c-b5bc-d9099d831713'), max_length=300),
        ),
    ]
