# Generated by Django 3.2.12 on 2022-06-15 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0068_auto_20220615_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('6231baf9-c312-4433-940c-64c1dba42b0f'), max_length=300),
        ),
    ]
