# Generated by Django 3.2.12 on 2022-06-15 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0070_auto_20220615_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('43899741-de2e-46fe-a173-e5b26a3c6927'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='Alternative_Mobile',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='Mobile',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
