# Generated by Django 3.2.12 on 2022-06-16 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0071_auto_20220615_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5872d542-b226-4dc7-bf01-ec4e7cd40ab0'), max_length=300),
        ),
    ]
