# Generated by Django 3.2.12 on 2022-06-16 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0073_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('aa43ba48-cf6a-45ff-abab-5f9b173f6a62'), max_length=300),
        ),
    ]
