# Generated by Django 3.2.12 on 2022-06-16 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0074_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('4c85a3c1-ac0f-415c-a265-b511d63c0117'), max_length=300),
        ),
    ]
