# Generated by Django 3.2.12 on 2022-06-16 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0075_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('2a75ecfb-b08e-4533-8c55-e06d6bc50d14'), max_length=300),
        ),
    ]
