# Generated by Django 3.2.12 on 2022-06-16 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0076_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('064219f3-235f-4189-ad93-0e19fb7bf52c'), max_length=300),
        ),
    ]
