# Generated by Django 3.2.12 on 2022-06-16 16:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0077_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('852eef19-bb7a-44cc-ac1d-25f7ce146e06'), max_length=300),
        ),
    ]
