# Generated by Django 3.2.12 on 2022-06-16 16:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0078_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('30a9b682-936a-4ca0-918d-945e3a1014e3'), max_length=300),
        ),
    ]
