# Generated by Django 3.2.12 on 2022-06-17 13:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0079_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('75d61cb9-cac7-46fb-b7b0-71ba31cc274f'), max_length=300),
        ),
        migrations.CreateModel(
            name='request_a_quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=400)),
                ('lname', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=300)),
                ('event_type', models.CharField(max_length=400)),
                ('appx_date', models.DateField()),
                ('no_of_guests', models.CharField(max_length=300)),
                ('msg', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
