# Generated by Django 3.2.12 on 2022-06-19 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0080_auto_20220617_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('42797c3f-8e93-42ae-962f-5981f6b4b2b8'), max_length=300),
        ),
    ]
