# Generated by Django 3.2.12 on 2022-06-24 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0082_auto_20220619_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_a_quote',
            name='v_link',
            field=models.CharField(default='no', max_length=200),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('21160151-6d97-4d7a-b796-070dd6a86f1e'), max_length=300),
        ),
    ]
