# Generated by Django 3.2.12 on 2022-06-25 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0083_auto_20220624_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('aad736a8-e6e3-43ec-b706-4a779b4d2a14'), max_length=300),
        ),
        migrations.CreateModel(
            name='vendor_quote_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_id', models.CharField(max_length=300)),
                ('quotation_items', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('payment_terms', models.TextField()),
                ('valid_till', models.DateField()),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
