# Generated by Django 3.2.12 on 2022-06-25 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0084_auto_20220625_0430'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quote_invoice',
            name='link_id',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('fff93406-3291-4af0-b74f-d4bebabcdc81'), max_length=300),
        ),
    ]
