# Generated by Django 3.2.12 on 2022-06-25 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0086_auto_20220625_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_quote_invoice',
            name='quote_user',
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('35ed9f0e-57a2-4d8e-b216-48ba531333c2'), max_length=300),
        ),
    ]
