# Generated by Django 3.2.12 on 2022-06-25 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0088_auto_20220625_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quote_invoice',
            name='short_link',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('e9c07006-d5f1-4734-81da-cd7fc95af811'), max_length=300),
        ),
    ]
