# Generated by Django 3.2.12 on 2022-06-26 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0090_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('6da979ec-75cc-40d4-a252-6e30775accb9'), max_length=300),
        ),
    ]
