# Generated by Django 3.2.12 on 2022-06-27 07:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0091_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_a_quote',
            name='quote_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_quote_invoice'),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('602278d4-b275-444a-b2b2-6dff948f44b5'), max_length=300),
        ),
    ]
