# Generated by Django 3.2.12 on 2022-06-29 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0093_auto_20220629_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quote_invoice',
            name='total_amt',
            field=models.CharField(default='0', max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('d7af65d6-e6a7-4bde-8d9d-feb8f7adcede'), max_length=300),
        ),
    ]
