# Generated by Django 3.2.12 on 2022-06-30 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0094_auto_20220629_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('2a2d8313-ee6e-4a81-a59f-1e2392cf7cbc'), max_length=300),
        ),
    ]
