# Generated by Django 3.2.12 on 2022-06-30 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0095_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='vendor_wallet',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('d539c067-9b0d-4eed-96c2-952cb7b2c03d'), max_length=300),
        ),
    ]
