# Generated by Django 3.2.12 on 2022-07-02 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0097_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('0c8410d4-ea76-46c4-8a3e-76450a2b24e5'), max_length=300),
        ),
    ]
