# Generated by Django 3.2.12 on 2022-07-02 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0098_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9852f110-c37e-4668-9130-a493f6772ba2'), max_length=300),
        ),
    ]
