# Generated by Django 3.2.12 on 2022-07-02 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0099_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('100a2a93-5c28-4b57-bd51-fac43414dc37'), max_length=300),
        ),
    ]
