# Generated by Django 3.2.12 on 2022-07-02 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0100_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('698dec49-0d29-4e92-bc36-dca83387e817'), max_length=300),
        ),
    ]
