# Generated by Django 3.2.12 on 2022-07-02 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0101_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total_sales',
            name='Apr_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Aug_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Dec_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Feb_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Jan_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Jul_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Jun_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Mar_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='May_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Nov_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Oct_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='total_sales',
            name='Sep_sales',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('df0d2d1c-349b-403b-9c11-94442407eb39'), max_length=300),
        ),
    ]
