# Generated by Django 3.2.12 on 2022-07-02 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0102_auto_20220702_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='location_country_code',
            field=models.CharField(blank=True, default='24', max_length=400),
        ),
        migrations.AddField(
            model_name='vendor_public_packages',
            name='location_state_code',
            field=models.CharField(blank=True, default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('b0b83859-2767-4c9c-b0d5-706f62a93cd9'), max_length=300),
        ),
    ]
