# Generated by Django 3.2.12 on 2022-07-06 17:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content_app', '0024_alter_venue_details_venue_name'),
        ('vendor_admin', '0103_auto_20220702_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='event_categories',
            field=models.ForeignKey(blank=True, default=3, on_delete=django.db.models.deletion.CASCADE, to='content_app.event_categories'),
        ),
        migrations.AddField(
            model_name='vendor_users',
            name='event_subcat',
            field=models.CharField(default='none', max_length=400),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('e2ab86f5-48de-4307-b94a-0e84dd1a7bbe'), max_length=300),
        ),
    ]
