# Generated by Django 3.2.12 on 2022-07-07 12:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0104_auto_20220706_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='vendor_cat',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories'),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5486da00-abc0-4100-959f-0108392e8b47'), max_length=300),
        ),
    ]
