# Generated by Django 3.2.12 on 2022-07-07 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0105_auto_20220707_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_users',
            name='vendor_cat',
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('a7322d52-3d95-432b-825d-c51f8e93a3fb'), max_length=300),
        ),
    ]
