# Generated by Django 3.2.12 on 2022-07-07 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0106_auto_20220707_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('916e6bcf-02a6-4905-b050-eb8973272072'), max_length=300),
        ),
    ]
