# Generated by Django 3.2.12 on 2022-07-07 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0107_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('7a1df6ab-9b1b-41e9-9439-ba26e5b630b0'), max_length=300),
        ),
    ]
