# Generated by Django 3.2.12 on 2022-07-09 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0109_auto_20220709_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ab9974c5-47a6-41e4-895e-090922586fe2'), max_length=300),
        ),
    ]
