# Generated by Django 3.2.12 on 2022-07-10 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0110_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('e5b97e90-1a63-490d-8ce8-4777f52827ed'), max_length=300),
        ),
        migrations.CreateModel(
            name='search_cms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_subheading', models.CharField(max_length=300)),
                ('search_image', models.ImageField(upload_to='search_content/image/detailed/')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories')),
            ],
        ),
    ]
