# Generated by Django 3.2.12 on 2022-07-11 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0111_auto_20220710_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='image',
            field=models.ImageField(default=0, upload_to='vendor_public_packages/images/'),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9ca9d7ae-4bdc-4787-940d-b3b94bfc3da6'), max_length=300),
        ),
    ]
