# Generated by Django 3.2.12 on 2022-07-19 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0112_auto_20220711_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='attendee_range',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('cda48ed4-7a9d-4370-b96f-e37340323988'), max_length=300),
        ),
    ]
