# Generated by Django 3.2.12 on 2022-07-19 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0113_auto_20220719_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='pricing_model',
            field=models.CharField(default='0', max_length=400),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5c6b6602-a0cc-4a82-8f61-ec2dcc5cbc65'), max_length=300),
        ),
    ]
