# Generated by Django 3.2.12 on 2022-07-21 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0114_auto_20220719_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('3a66ebeb-8b63-4eb3-8eb1-b66518856b38'), max_length=300),
        ),
    ]
