# Generated by Django 3.2.12 on 2022-07-22 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0115_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('26eb1c0f-28da-4ba0-8b49-2c379180f1ed'), max_length=300),
        ),
    ]
