# Generated by Django 3.2.12 on 2022-07-23 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0118_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('48bb3dd1-92e9-40e5-80ce-ef9b60460347'), max_length=300),
        ),
    ]
