# Generated by Django 3.2.12 on 2022-07-24 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0119_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='profile_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('46f63df7-141c-4f60-b5f8-6900b49a9029'), max_length=300),
        ),
    ]
