# Generated by Django 3.2.12 on 2022-07-24 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0120_auto_20220724_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c319948c-b159-4384-b1be-4a6819e4d178'), max_length=300),
        ),
    ]
