# Generated by Django 3.2.12 on 2022-07-28 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0121_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('4ae6bd70-b52f-4c3e-be06-0cd8e50e7442'), max_length=300),
        ),
    ]
