# Generated by Django 3.2.12 on 2022-07-28 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0122_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5773188d-9d78-4486-ae68-c0281affbf7d'), max_length=300),
        ),
    ]
