# Generated by Django 3.2.12 on 2022-07-30 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0123_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5eda5817-2bdc-4746-8783-d85c5109467d'), max_length=300),
        ),
    ]
