# Generated by Django 3.2.12 on 2022-08-04 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0124_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('32c037de-b264-41bd-9c41-16f72136078a'), max_length=300),
        ),
        
        migrations.AlterField(
            model_name='vendor_subscription',
            name='package_fee',
            field=models.BigIntegerField(blank=True, default=123),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='service_fee',
            field=models.BigIntegerField(blank=True, default=12),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='vendor_categories',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='vendor_phone',
            field=models.BigIntegerField(blank=True, default=123),
        ),
    ]
