# Generated by Django 3.2.12 on 2022-08-04 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0125_auto_20220804_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('5b51e1f7-0a5a-4708-9625-a8db9a45b79e'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='country_cuurency',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='vendor_categories',
            field=models.CharField(max_length=400),
        ),
    ]
