# Generated by Django 3.2.12 on 2022-08-04 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0126_auto_20220804_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('31ac4bb0-20b0-411f-946a-3e47c2e5c2e2'), max_length=300),
        ),
    ]
