# Generated by Django 3.2.12 on 2022-08-06 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0129_auto_20220805_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9948aaaa-5d98-4aaf-b050-b89a8c233b1f'), max_length=300),
        ),
    ]
