# Generated by Django 3.2.12 on 2022-08-06 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0130_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_packages',
            name='package_price_range_max',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_public_packages',
            name='package_price_range_min',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('e799c8d8-0981-482e-bd65-caa2facff7ef'), max_length=300),
        ),
    ]
