# Generated by Django 3.2.12 on 2022-08-07 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0131_auto_20220806_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('10895b68-0e9e-464b-b517-9256c54377ff'), max_length=300),
        ),
        migrations.CreateModel(
            name='vendor_public_deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_price', models.CharField(max_length=4000)),
                ('deal_disc_percent', models.CharField(max_length=4000)),
                ('package_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_public_packages')),
            ],
        ),
    ]
