# Generated by Django 4.1 on 2022-08-07 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0133_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings_data',
            name='DnR',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='atmosphere_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='capacity_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='caterer_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='event_planner_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='feature_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='photo_vdo_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='listings_data',
            name='speciality_sets',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('03e61e01-c287-428e-8390-f28ea9bed81f'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_quote_invoice',
            name='quotation_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='caterer_field',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='event_category_serve',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='question_field',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vendor_users',
            name='vendor_categories',
            field=models.JSONField(default=dict),
        ),
    ]
