# Generated by Django 4.1 on 2022-08-08 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0135_vendor_subscription_service_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('d03888cf-fb0e-492d-9074-0f9c0f2edeb5'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='service_fee',
            field=models.FloatField(blank=True, default=12),
        ),
    ]
