# Generated by Django 4.1 on 2022-08-08 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0136_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('d57fbdbf-51ca-4ac6-8978-0a7a5778ba45'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_subscription',
            name='service_currency',
            field=models.CharField(default='USD', max_length=300),
        ),
    ]
