# Generated by Django 4.1 on 2022-08-11 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0137_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('db1db8f6-71a2-4ae1-bb79-59f5c345b17e'), max_length=300),
        ),
    ]
