# Generated by Django 4.1 on 2022-08-12 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0138_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('71aa3c3a-cf08-4c1f-8eaa-ed3b37d81b3b'), max_length=300),
        ),
    ]
