# Generated by Django 4.1 on 2022-08-12 16:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0140_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ffeef927-4143-4fe0-8ea2-af04c56e4783'), max_length=300),
        ),
    ]
