# Generated by Django 4.1 on 2022-08-13 05:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0143_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9e7c536b-2ac6-4b9e-ba04-3ad544c11af0'), max_length=300),
        ),
    ]
