# Generated by Django 4.1 on 2022-08-13 05:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0144_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('455703c8-a5cc-42db-957c-5b3d3402913a'), max_length=300),
        ),
    ]
