# Generated by Django 4.1 on 2022-08-13 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0145_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('4eaa5581-66d0-4085-babd-cfce9315c82b'), max_length=300),
        ),
    ]
