# Generated by Django 4.1 on 2022-08-13 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0146_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('89cc4190-cc64-46b0-aaea-ae53e9a549c0'), max_length=300),
        ),
    ]
