# Generated by Django 4.1 on 2022-08-13 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0148_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('23e4a6a5-4f22-4d8c-a813-11d8ab05b654'), max_length=300),
        ),
    ]
