# Generated by Django 4.1 on 2022-08-13 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0150_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ea559f70-737c-40ff-9095-a8ce966ed992'), max_length=300),
        ),
    ]
