# Generated by Django 4.1 on 2022-08-13 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0151_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('0154a68e-cb68-4ac6-abe4-be945b4ae2f0'), max_length=300),
        ),
    ]
