# Generated by Django 4.1 on 2022-08-13 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0152_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c72bc661-982b-4f72-a99d-12821e9e60f1'), max_length=300),
        ),
    ]
