# Generated by Django 4.1 on 2022-08-16 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0154_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('03570cff-4f78-430d-9a2c-07e0b0f91e66'), max_length=300),
        ),
    ]
