# Generated by Django 4.1 on 2022-08-16 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0155_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('0732b667-9ab4-4f7e-a157-3520c2f2f35f'), max_length=300),
        ),
    ]
