# Generated by Django 4.1 on 2022-08-16 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0156_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('15114da3-7767-4dd3-9564-41bcc0d1e743'), max_length=300),
        ),
    ]
