# Generated by Django 4.1 on 2022-08-16 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0157_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('65c8c20c-9976-48ee-ba35-0b4792156ff1'), max_length=300),
        ),
    ]
