# Generated by Django 4.1 on 2022-08-16 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0158_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('f51fe5bd-77cf-4f66-ac58-3b09472041a0'), max_length=300),
        ),
    ]
