# Generated by Django 4.1 on 2022-08-16 16:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0159_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9d4ced75-afd8-4f1c-8070-5c5ffe8ea73d'), max_length=300),
        ),
    ]
