# Generated by Django 4.1 on 2022-08-17 08:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0160_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('34a24947-7044-48db-9898-1350630ca594'), max_length=300),
        ),
    ]
