# Generated by Django 4.1 on 2022-08-17 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0161_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('808c59d3-1116-4fe4-b3b8-0fc1eab15f72'), max_length=300),
        ),
    ]
