# Generated by Django 4.1 on 2022-08-18 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0162_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('63accbe8-b585-4a87-aabe-e71b0eab206a'), max_length=300),
        ),
    ]
