# Generated by Django 4.1 on 2022-08-18 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0164_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('43f8e4c1-7309-4e38-9a22-0cd5f2adcecd'), max_length=300),
        ),
    ]
