# Generated by Django 4.1 on 2022-08-19 08:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0165_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('64f4f20e-e565-4dde-bdfa-5c8d5e046fe3'), max_length=300),
        ),
        migrations.CreateModel(
            name='Vendor_bank_listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank_Name', models.CharField(max_length=1000)),
                ('Account_Name', models.CharField(max_length=1000)),
                ('Bank_Account_Number', models.CharField(max_length=4000)),
                ('Country', models.CharField(max_length=1000)),
                ('Code_Banque', models.CharField(max_length=2000)),
                ('Code_Guichet', models.CharField(max_length=3000)),
                ('Cle_RIB', models.CharField(max_length=3000)),
                ('IBAN', models.CharField(max_length=5000)),
                ('Code_Swift', models.CharField(max_length=4000)),
                ('Domiciliation', models.CharField(max_length=3000)),
                ('Vendor_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
