# Generated by Django 4.1 on 2022-08-19 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0166_alter_vendor_gallery_photo_id_vendor_bank_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('92f77925-26aa-4c95-b3c3-35dacfc2937b'), max_length=300),
        ),
    ]
