# Generated by Django 4.1 on 2022-08-19 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0167_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('945df0fd-2d56-45dc-a46e-95f3b6c4726f'), max_length=300),
        ),
    ]
