# Generated by Django 4.1 on 2022-08-19 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0169_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='MoMo_Number',
            field=models.CharField(default=0, max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='PayPal_Account_Name',
            field=models.CharField(default=0, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='Paypal_ID',
            field=models.CharField(default=0, max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9258a59c-c0aa-4aea-86fe-778ac6df86d9'), max_length=300),
        ),
    ]
