# Generated by Django 4.1 on 2022-08-21 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0170_vendor_bank_listing_momo_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('b153a730-6dfb-4483-b309-43a295a9928f'), max_length=300),
        ),
    ]
