# Generated by Django 4.1 on 2022-08-21 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0171_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('bba469a1-e148-4f7a-8d32-e6bd3c2a1a83'), max_length=300),
        ),
    ]
