# Generated by Django 4.1 on 2022-08-22 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0172_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_public_deals',
            old_name='deal_disc_percent',
            new_name='deal_by',
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c5e6e8b9-927b-4d86-a74d-385a63fda0f1'), max_length=300),
        ),
    ]
