# Generated by Django 4.1 on 2022-08-22 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0173_rename_deal_disc_percent_vendor_public_deals_deal_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_deals',
            name='deal_name',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('1277ab09-1717-4b57-9928-8df30517ec6a'), max_length=300),
        ),
    ]
