# Generated by Django 4.1 on 2022-08-22 09:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0174_vendor_public_deals_deal_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('60d9980b-6f38-4320-ac96-046b6d3b836e'), max_length=300),
        ),
        migrations.CreateModel(
            name='vendor_filter_answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_questions')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users')),
            ],
        ),
    ]
