# Generated by Django 4.1 on 2022-08-23 17:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0175_alter_vendor_gallery_photo_id_vendor_filter_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('e05c7741-5152-450a-bdde-c8935a9d8c3b'), max_length=300),
        ),
    ]
