# Generated by Django 4.1 on 2022-08-24 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0176_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('4a68cbea-6211-463e-9a41-07224ea69737'), max_length=300),
        ),
    ]
