# Generated by Django 4.1 on 2022-08-24 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0177_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c716a842-e342-4483-adc3-2e6ddb630d1d'), max_length=300),
        ),
    ]
