# Generated by Django 4.1 on 2022-08-24 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0178_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ae490ae4-a2ed-46e9-819f-6c71c75c6b65'), max_length=300),
        ),
    ]
