# Generated by Django 4.1 on 2022-08-24 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0179_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('0a462722-b935-4a52-885e-26461d33ce85'), max_length=300),
        ),
    ]
