# Generated by Django 4.1 on 2022-08-24 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0180_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9d13d8c3-9024-4695-a8fd-caf3ce6b6cb5'), max_length=300),
        ),
    ]
