# Generated by Django 4.1 on 2022-08-31 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0182_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ff6c1676-a46b-43b8-8fab-d707285a11de'), max_length=300),
        ),
    ]
