# Generated by Django 4.1 on 2022-09-04 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0184_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('cbba9a1b-8636-4ecc-b0b0-57a243e30ab3'), max_length=300),
        ),
    ]
