# Generated by Django 4.1 on 2022-09-06 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0186_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('338fe499-2b43-48c0-9e9f-d11926051312'), max_length=300),
        ),
    ]
