# Generated by Django 4.1 on 2022-09-06 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0187_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('d16e91d9-52e9-4e61-b26d-2800c20a272f'), max_length=300),
        ),
    ]
