# Generated by Django 4.1 on 2022-09-07 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0188_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('0341a6ec-c60d-4288-9971-24bbc647a15c'), max_length=300),
        ),
    ]
