# Generated by Django 4.1 on 2022-09-07 12:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0189_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('9d7311e0-29bd-46c5-ba1c-5419a8688931'), max_length=300),
        ),
    ]
