# Generated by Django 4.1 on 2022-09-13 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0190_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('2bb16d5b-10e0-4983-b7e7-08690c27cc0a'), max_length=300),
        ),
    ]
