# Generated by Django 4.1 on 2022-09-15 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0191_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('f20c3e1d-f9d4-42bd-8568-e0a2dad1d74d'), max_length=300),
        ),
    ]
