# Generated by Django 4.1 on 2022-09-15 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0192_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_deals',
            name='vendor_id',
            field=models.ForeignKey(default=101, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('62f5a9c0-0e40-4c4a-8e8d-cbd0936cbedd'), max_length=300),
        ),
    ]
