# Generated by Django 4.1 on 2022-09-15 17:58

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0193_vendor_public_deals_vendor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_public_deals',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('458a804c-8a63-4e9b-9b49-05d989d8cb63'), max_length=300),
        ),
    ]
