# Generated by Django 4.1 on 2022-09-20 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0194_vendor_public_deals_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('4876558b-e1e1-41ac-9c77-08f4cc07442a'), max_length=300),
        ),
    ]
