# Generated by Django 4.1 on 2022-10-01 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0196_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='vendor_leads_package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=5000)),
                ('package_desc', models.TextField()),
                ('package_fee', models.CharField(help_text='In FCFA', max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_type', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('278627e5-a881-4129-a401-d998871ddd77'), max_length=300),
        ),
    ]
