# Generated by Django 4.1 on 2022-10-01 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0197_vendor_leads_package_alter_vendor_gallery_photo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('7f20f98e-66b1-427c-bba4-1b782fc1a351'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year'), ('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
