# Generated by Django 4.1 on 2022-10-02 05:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0198_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_leads_package',
            name='package_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='leads_package/vendor/files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('7500e47e-caed-4351-a6ba-a100cb37640d'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Year', 'Year'), ('Month', 'Month'), ('Quarter', 'Quarter')], max_length=4000),
        ),
    ]
