# Generated by Django 4.1 on 2022-10-02 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0199_vendor_leads_package_package_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_leads_package',
            name='lead_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('80b4551b-dc48-425a-8908-9a7978fcced9'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Quarter', 'Quarter'), ('Month', 'Month'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
