# Generated by Django 4.1 on 2022-10-04 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0200_vendor_leads_package_lead_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('be6030ac-25bd-4db9-b29f-b4e55b3be150'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly'), ('Year', 'Year'), ('Month', 'Month')], max_length=4000),
        ),
    ]
