# Generated by Django 4.1 on 2022-10-05 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0202_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('2c28f5e3-0b23-4092-ace6-a6a269197571'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Half-Yearly', 'Half-Yearly'), ('Quarter', 'Quarter'), ('Month', 'Month')], max_length=4000),
        ),
    ]
