# Generated by Django 4.1 on 2022-10-05 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0203_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('50898887-fd1f-4993-9083-1d5c17f92d52'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Month', 'Month'), ('Year', 'Year'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
