# Generated by Django 4.1 on 2022-10-05 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0204_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('f9815993-56ff-4b96-b849-9152b2b1a22a'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly'), ('Month', 'Month'), ('Year', 'Year')], max_length=4000),
        ),
    ]
