# Generated by Django 4.1 on 2022-10-08 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0206_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('2a1315f8-b9a7-4757-b9f7-e543c46772f7'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Quarter', 'Quarter'), ('Month', 'Month'), ('Year', 'Year')], max_length=4000),
        ),
    ]
