# Generated by Django 4.1 on 2022-10-08 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0209_request_a_quote_pay_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('7c4ce582-16c8-4f37-a728-4dd7b33a7e0b'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Month', 'Month'), ('Quarter', 'Quarter'), ('Year', 'Year'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
