# Generated by Django 4.1 on 2022-10-12 17:09

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0213_vendor_faq_created_at_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_packages',
            name='package_description',
            field=tinymce.models.HTMLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_faq',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='deactive', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('af3d7f1d-6d60-4a1a-91af-184650ac85f2'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Month', 'Month'), ('Year', 'Year'), ('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
