# Generated by Django 4.1 on 2022-10-12 17:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0214_vendor_packages_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('ad63d8df-86f6-486d-9fa1-471d575dc2c5'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
        migrations.AlterField(
            model_name='vendor_packages',
            name='package_description',
            field=models.TextField(),
        ),
    ]
