# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0215_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request_a_quote',
            options={'verbose_name_plural': 'Request A Quote - Entries'},
        ),
        migrations.AlterModelOptions(
            name='search_cms',
            options={'verbose_name_plural': 'Search CMS'},
        ),
        migrations.AlterModelOptions(
            name='vendor_bank_listing',
            options={'verbose_name_plural': 'Vendor Bank Details'},
        ),
        migrations.AlterModelOptions(
            name='vendor_faq',
            options={'verbose_name_plural': 'Vendor FAQ Page'},
        ),
        migrations.AlterModelOptions(
            name='vendor_gallery',
            options={'verbose_name_plural': 'Vendor Gallery'},
        ),
        migrations.AlterModelOptions(
            name='vendor_leads_package',
            options={'verbose_name_plural': 'Vendor Leads - Package'},
        ),
        migrations.AlterModelOptions(
            name='vendor_public_packages',
            options={'verbose_name_plural': 'Vendor Hosted Packages'},
        ),
        migrations.AlterModelOptions(
            name='vendor_questions',
            options={'verbose_name_plural': 'Vendor Features'},
        ),
        migrations.AlterField(
            model_name='vendor_faq',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('485d4b64-6f50-4597-abae-5322775f8a0f'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Quarter', 'Quarter'), ('Month', 'Month'), ('Year', 'Year')], max_length=4000),
        ),
        migrations.AlterField(
            model_name='vendor_quote_invoice',
            name='milestone',
            field=models.FloatField(default=0, max_length=300),
        ),
    ]
