# Generated by Django 4.1 on 2022-10-17 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0216_alter_request_a_quote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_quote_invoice',
            name='tax_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('78fdb246-67ae-46d2-bffd-39b97018175d'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
