# Generated by Django 4.1 on 2022-10-17 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0218_alter_vendor_faq_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='is_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='is_momo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor_bank_listing',
            name='is_paypal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendor_faq',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('84c62619-6e6b-4a68-b578-dd12acfc56ae'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly'), ('Year', 'Year'), ('Month', 'Month')], max_length=4000),
        ),
    ]
