# Generated by Django 4.1 on 2022-10-18 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0219_vendor_bank_listing_is_bank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_users',
            name='city_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('aea5c49e-251d-4d9b-97b4-299a0f43b099'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Half-Yearly', 'Half-Yearly'), ('Quarter', 'Quarter'), ('Month', 'Month')], max_length=4000),
        ),
    ]
