# Generated by Django 4.1 on 2022-10-19 10:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0221_alter_vendor_faq_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_faq',
            name='status',
            field=models.CharField(choices=[('deactive', 'deactive'), ('active', 'active')], default='deactive', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('834d77bc-7add-4dbb-bc3b-55527317dbed'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Half-Yearly', 'Half-Yearly'), ('Quarter', 'Quarter')], max_length=4000),
        ),
    ]
