# Generated by Django 4.1 on 2022-10-19 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0222_alter_vendor_faq_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_categories',
            name='thumbnail_cover_image',
            field=models.ImageField(default=0, upload_to='vendors/thumbnail/categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('cb22989f-f3ff-4cd9-a68b-4d35f4181471'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Half-Yearly', 'Half-Yearly'), ('Month', 'Month'), ('Quarter', 'Quarter')], max_length=4000),
        ),
    ]
