# Generated by Django 4.1 on 2022-10-22 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0224_alter_vendor_faq_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('382839e5-31c0-4a70-9759-d68e6e9aabf5'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Half-Yearly', 'Half-Yearly'), ('Year', 'Year'), ('Quarter', 'Quarter'), ('Month', 'Month')], max_length=4000),
        ),
    ]
