# Generated by Django 4.1 on 2022-10-28 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0225_alter_vendor_gallery_photo_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('38b4d593-0dc0-42f4-b003-56619899c61d'), max_length=300),
        ),
    ]
