# Generated by Django 4.1 on 2022-12-08 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0228_alter_vendor_faq_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_packages',
            name='lead_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('b2afadd9-b504-4a7c-8363-c8ec76430f26'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Quarter', 'Quarter'), ('Month', 'Month'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
