# Generated by Django 4.1 on 2022-12-16 09:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0229_vendor_packages_lead_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor_gallery',
            name='photo_id',
            field=models.CharField(default=uuid.UUID('c1f8cce6-5821-4881-981f-c8d3a634fa64'), max_length=300),
        ),
        migrations.AlterField(
            model_name='vendor_leads_package',
            name='valid_type',
            field=models.CharField(choices=[('Year', 'Year'), ('Month', 'Month'), ('Quarter', 'Quarter'), ('Half-Yearly', 'Half-Yearly')], max_length=4000),
        ),
    ]
