# Generated by Django 3.2.12 on 2022-06-08 07:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20220608_0742'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='category',
        # ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('0b83bf4c-9961-464e-bf69-b4de7c34389c'), max_length=400),
        ),
    ]
