# Generated by Django 3.2.12 on 2022-06-08 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20220608_0759'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='blog_category',
        # ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('89d35963-b9a3-4280-adae-55e46a382cb4'), max_length=400),
        ),
    ]
