# Generated by Django 3.2.12 on 2022-06-08 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_post_blog_id'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='blog_category',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('category_img', models.ImageField(upload_to='main_site/blog/categories/img')),
        #         ('category_name', models.CharField(max_length=300)),
        #     ],
        # ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6ef149ab-9cc6-4158-bb0b-1280a29f1616'), max_length=400),
        ),
    ]
