# Generated by Django 3.2.12 on 2022-06-08 14:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20220608_1442'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='post',
        #     name='category',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogs.blog_category'),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('985f1fde-fb1b-47b0-a1d0-d56feb8393fc'), max_length=400),
        ),
    ]
