# Generated by Django 3.2.12 on 2022-06-08 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_auto_20220608_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d6aff618-ed33-4b88-8eab-bc8d21b9e50c'), max_length=400),
        ),
    ]
