# Generated by Django 3.2.12 on 2022-06-08 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a5275b8c-ccc2-4dc9-88fe-d479f3831fac'), max_length=400),
        ),
    ]
