# Generated by Django 3.2.12 on 2022-06-08 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category',
            options={'verbose_name_plural': 'Blog Categories'},
        ),
    ]
