# Generated by Django 3.2.12 on 2022-06-08 16:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0014_blog_cms_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('082e286d-e71d-4585-8534-560eb73f573b'), editable=False, max_length=400, unique=True),
        ),
    ]
