# Generated by Django 3.2.12 on 2022-06-08 16:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0016_auto_20220608_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('59ee6376-0731-42f2-8c82-27529c66f700'), editable=False, max_length=400, unique=True),
        ),
    ]
