# Generated by Django 3.2.12 on 2022-06-08 18:53

from django.db import migrations, models
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0017_auto_20220608_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('79b60f03-0362-48a5-8b8b-b1f768b6392c'), editable=False, max_length=400, unique=True),
        ),
    ]
