# Generated by Django 3.2.12 on 2022-06-08 19:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0019_auto_20220608_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e4a27624-67d0-445e-8695-ede9d006fb5d'), editable=False, max_length=400, unique=True),
        ),
    ]
