# Generated by Django 3.2.12 on 2022-06-08 19:28

from django.db import migrations, models
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0020_alter_post_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='uploaded_images')),
                ('cropping', image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('744110bd-9f39-48b3-bc51-66ce1d9d0a03'), editable=False, max_length=400, unique=True),
        ),
    ]
