# Generated by Django 3.2.12 on 2022-06-08 19:32

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0021_auto_20220608_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_field', image_cropping.fields.ImageCropField(upload_to='image/')),
                ('cropping', image_cropping.fields.ImageRatioField('image_field', '120x100', adapt_rotation=False, allow_fullsize=True, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('cropping_free', image_cropping.fields.ImageRatioField('image_field', '300x230', adapt_rotation=False, allow_fullsize=False, free_crop=True, help_text=None, hide_image_field=False, size_warning=True, verbose_name='cropping free')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropping', image_cropping.fields.ImageRatioField('image__image_field', '120x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.image')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('0f4a3a51-fc92-4baa-bfb0-f64e8b763c1a'), editable=False, max_length=400, unique=True),
        ),
    ]
