# Generated by Django 3.2.12 on 2022-06-08 19:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0022_auto_20220608_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefk',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a2a1bd60-8d51-4b03-a565-3c2c76a1396c'), editable=False, max_length=400, unique=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='ImageFK',
        ),
    ]
