# Generated by Django 3.2.12 on 2022-06-10 03:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0023_auto_20220608_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('2540ed3d-1a0f-4eb2-9add-531907160e56'), editable=False, max_length=400, unique=True),
        ),
    ]
