# Generated by Django 3.2.12 on 2022-06-10 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0024_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('8ee516d3-b0b3-49b3-a8e5-b1231770e9a5'), editable=False, max_length=400, unique=True),
        ),
    ]
