# Generated by Django 3.2.12 on 2022-06-10 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0025_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('c881457d-f5ac-4de0-b6f1-395f148dbc28'), editable=False, max_length=400, unique=True),
        ),
    ]
