# Generated by Django 3.2.12 on 2022-06-10 07:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0026_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a6fcd697-457e-48f0-81ac-5a8d25f82623'), editable=False, max_length=400, unique=True),
        ),
    ]
