# Generated by Django 3.2.12 on 2022-06-10 07:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0027_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9b8963df-0089-45e7-b134-f3fe7099bfa0'), editable=False, max_length=400, unique=True),
        ),
    ]
