# Generated by Django 3.2.12 on 2022-06-10 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0028_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('96f1f195-3fb8-4eb1-a04c-6e9cad172cfa'), editable=False, max_length=400, unique=True),
        ),
    ]
