# Generated by Django 3.2.12 on 2022-06-10 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0029_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('2661b416-ac3c-4225-8a9e-486e643145dc'), editable=False, max_length=400, unique=True),
        ),
    ]
