# Generated by Django 3.2.12 on 2022-06-10 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0035_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('82cb0965-2e36-4330-a659-c00a6c73fb56'), editable=False, max_length=400, unique=True),
        ),
    ]
