# Generated by Django 3.2.12 on 2022-06-11 06:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0036_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('92437c93-2853-42d0-b102-7711b41c2ab1'), editable=False, max_length=400, unique=True),
        ),
    ]
