# Generated by Django 3.2.12 on 2022-06-11 06:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0038_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('516b40f9-b355-42c6-9b62-f71f3f818ee3'), editable=False, max_length=400, unique=True),
        ),
    ]
