# Generated by Django 3.2.12 on 2022-06-12 04:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0040_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('b7c567c6-fd20-453e-bf4f-8125b8c5ce98'), editable=False, max_length=400, unique=True),
        ),
    ]
