# Generated by Django 3.2.12 on 2022-06-12 06:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0041_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6a008ef0-d2d3-46df-9ff7-d7fbca37b072'), editable=False, max_length=400, unique=True),
        ),
    ]
