# Generated by Django 3.2.12 on 2022-06-12 06:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0042_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d890f4a3-5655-4393-9e10-4f3ee84c9214'), editable=False, max_length=400, unique=True),
        ),
    ]
