# Generated by Django 3.2.12 on 2022-06-12 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0043_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('19f6a37b-7ad1-4a77-854c-43aee5a4f504'), editable=False, max_length=400, unique=True),
        ),
    ]
