# Generated by Django 3.2.12 on 2022-06-12 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0044_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('5357b892-136a-4f2c-b4b4-0a8cd67b4139'), editable=False, max_length=400, unique=True),
        ),
    ]
