# Generated by Django 3.2.12 on 2022-06-12 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0045_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('922e591e-c0c9-45a2-9104-4c1e07f5af73'), editable=False, max_length=400, unique=True),
        ),
    ]
