# Generated by Django 3.2.12 on 2022-06-12 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0046_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('5eca63c4-851f-41be-bd6f-19fcb0b066ec'), editable=False, max_length=400, unique=True),
        ),
    ]
