# Generated by Django 3.2.12 on 2022-06-12 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0047_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('71e48372-9b98-4d9c-856b-b641f6986442'), editable=False, max_length=400, unique=True),
        ),
    ]
