# Generated by Django 3.2.12 on 2022-06-12 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0048_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a51c87fd-b220-48a8-b561-4c12a823ad32'), editable=False, max_length=400, unique=True),
        ),
    ]
