# Generated by Django 3.2.12 on 2022-06-13 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0049_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e15b6060-8777-4874-b878-b039af9c6059'), editable=False, max_length=400, unique=True),
        ),
    ]
