# Generated by Django 3.2.12 on 2022-06-13 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0050_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('c3f5c28d-70a8-4587-b685-e99631b3e82b'), editable=False, max_length=400, unique=True),
        ),
    ]
