# Generated by Django 3.2.12 on 2022-06-13 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0051_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('ff57ee20-b6e9-4495-b902-1558c2098723'), editable=False, max_length=400, unique=True),
        ),
    ]
