# Generated by Django 3.2.12 on 2022-06-13 15:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0052_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4df1a402-4c79-41bd-8feb-7d6578a95851'), editable=False, max_length=400, unique=True),
        ),
    ]
