# Generated by Django 3.2.12 on 2022-06-13 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0054_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6322daf0-d260-44d1-be34-7eb55bdab092'), editable=False, max_length=400, unique=True),
        ),
    ]
