# Generated by Django 3.2.12 on 2022-06-13 15:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0055_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('f8deb85e-1287-4d6f-861c-b523e160f733'), editable=False, max_length=400, unique=True),
        ),
    ]
