# Generated by Django 3.2.12 on 2022-06-13 18:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0057_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('df1d3b94-bba2-446a-aed9-499e7a5cb62a'), editable=False, max_length=400, unique=True),
        ),
    ]
