# Generated by Django 3.2.12 on 2022-06-13 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0058_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6091453c-9afe-448d-b647-31633f320df5'), editable=False, max_length=400, unique=True),
        ),
    ]
