# Generated by Django 3.2.12 on 2022-06-14 16:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0059_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('27eb4a24-a122-474e-a823-e0b4903e348c'), editable=False, max_length=400, unique=True),
        ),
    ]
