# Generated by Django 3.2.12 on 2022-06-14 19:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0060_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('fa53c8f3-6023-44e9-a3ac-4ceeebd1f238'), editable=False, max_length=400, unique=True),
        ),
    ]
