# Generated by Django 3.2.12 on 2022-06-15 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0062_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('deb900ed-9f04-48bf-be04-bc09ac230b41'), editable=False, max_length=400, unique=True),
        ),
    ]
