# Generated by Django 3.2.12 on 2022-06-15 06:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0063_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('ab923c0e-bddd-47ca-a732-e8121b82f0c9'), editable=False, max_length=400, unique=True),
        ),
    ]
