# Generated by Django 3.2.12 on 2022-06-15 11:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0064_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d4f47645-3a61-4abb-9a0c-09a10896ce9f'), editable=False, max_length=400, unique=True),
        ),
    ]
