# Generated by Django 3.2.12 on 2022-06-15 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0065_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('859b5417-8c10-4bda-8f30-bc35c8004d54'), editable=False, max_length=400, unique=True),
        ),
    ]
