# Generated by Django 3.2.12 on 2022-06-16 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0067_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('139353a6-71bc-4b60-a14a-72101573db27'), editable=False, max_length=400, unique=True),
        ),
    ]
