# Generated by Django 3.2.12 on 2022-06-16 15:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0068_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('ba7b28e5-776d-4f3a-85a1-8cf33e56f439'), editable=False, max_length=400, unique=True),
        ),
    ]
