# Generated by Django 3.2.12 on 2022-06-16 15:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0069_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('50963c53-6aa2-4085-a0d4-7061310013bd'), editable=False, max_length=400, unique=True),
        ),
    ]
