# Generated by Django 3.2.12 on 2022-06-16 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0070_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('05e51f33-77a0-4ea8-bc00-1765bcbe3caa'), editable=False, max_length=400, unique=True),
        ),
    ]
