# Generated by Django 3.2.12 on 2022-06-16 15:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0071_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('8da02e8f-09b1-4996-b25b-13dc5011a0db'), editable=False, max_length=400, unique=True),
        ),
    ]
