# Generated by Django 3.2.12 on 2022-06-17 13:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0074_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e7b6c822-706c-4cc2-97d2-3c04a6376fcd'), editable=False, max_length=400, unique=True),
        ),
    ]
