# Generated by Django 3.2.12 on 2022-06-19 04:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0075_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('939c0ed9-7ca8-4a0c-9eac-d17fc995db94'), editable=False, max_length=400, unique=True),
        ),
    ]
