# Generated by Django 3.2.12 on 2022-06-19 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0076_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d61dbc51-9f90-4034-8453-e8d98d99fc45'), editable=False, max_length=400, unique=True),
        ),
    ]
