# Generated by Django 3.2.12 on 2022-06-24 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0077_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e29d4165-7465-42ed-91b4-8ac142af5ba1'), editable=False, max_length=400, unique=True),
        ),
    ]
