# Generated by Django 3.2.12 on 2022-06-25 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0078_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('462174f4-59df-479d-b1a9-cefcc16dab65'), editable=False, max_length=400, unique=True),
        ),
    ]
