# Generated by Django 3.2.12 on 2022-06-25 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0079_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d0fac788-84aa-4a76-aed7-604af18571a2'), editable=False, max_length=400, unique=True),
        ),
    ]
