# Generated by Django 3.2.12 on 2022-06-25 07:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0082_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('60f6f49f-fe80-4e41-aa34-a3e283f4dc5b'), editable=False, max_length=400, unique=True),
        ),
    ]
