# Generated by Django 3.2.12 on 2022-06-25 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0083_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('ea421c26-5206-4cec-aefb-fb0c7a610a87'), editable=False, max_length=400, unique=True),
        ),
    ]
