# Generated by Django 3.2.12 on 2022-06-26 17:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0085_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3cdb58fb-3dca-4b65-a3f2-3734f1ea4281'), editable=False, max_length=400, unique=True),
        ),
    ]
