# Generated by Django 3.2.12 on 2022-06-27 07:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0086_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4b2e60c5-c1b9-4386-925c-14de788bdc37'), editable=False, max_length=400, unique=True),
        ),
    ]
