# Generated by Django 3.2.12 on 2022-06-29 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0088_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('15acb803-026b-438d-bdd7-1c234300a3bb'), editable=False, max_length=400, unique=True),
        ),
    ]
