# Generated by Django 3.2.12 on 2022-06-30 09:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0090_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d94d810b-a662-4dd3-b7aa-af0dbf1cb624'), editable=False, max_length=400, unique=True),
        ),
    ]
