# Generated by Django 3.2.12 on 2022-06-30 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0091_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('650a59fd-b393-4388-bbc6-ffb6de5220a6'), editable=False, max_length=400, unique=True),
        ),
    ]
