# Generated by Django 3.2.12 on 2022-07-02 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0092_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3b566961-00de-4942-8139-08956c855d24'), editable=False, max_length=400, unique=True),
        ),
    ]
