# Generated by Django 3.2.12 on 2022-07-02 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0093_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('8889db60-15df-426c-a113-57acca4d4aa7'), editable=False, max_length=400, unique=True),
        ),
    ]
