# Generated by Django 3.2.12 on 2022-07-02 11:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0095_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3881af3a-701e-43f9-8260-a050a8fbba50'), editable=False, max_length=400, unique=True),
        ),
    ]
