# Generated by Django 3.2.12 on 2022-07-02 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0096_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('66b6465a-97dc-45cf-ba92-cffe21348406'), editable=False, max_length=400, unique=True),
        ),
    ]
