# Generated by Django 3.2.12 on 2022-07-02 11:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0097_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('7245a9e7-0bf1-41ad-8460-1a36ef17fd7c'), editable=False, max_length=400, unique=True),
        ),
    ]
