# Generated by Django 3.2.12 on 2022-07-06 17:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0098_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('67635dcd-ca60-4db2-b021-639bae845b0f'), editable=False, max_length=400, unique=True),
        ),
    ]
