# Generated by Django 3.2.12 on 2022-07-07 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0099_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e81f6354-88b4-4fc4-ad2e-da77d1a321ee'), editable=False, max_length=400, unique=True),
        ),
    ]
