# Generated by Django 3.2.12 on 2022-07-07 12:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0100_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('5e332a8c-e867-4ce8-91e7-22371b598160'), editable=False, max_length=400, unique=True),
        ),
    ]
