# Generated by Django 3.2.12 on 2022-07-07 13:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0101_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('988f098a-ec88-4076-a44e-511af97ff73d'), editable=False, max_length=400, unique=True),
        ),
    ]
