# Generated by Django 3.2.12 on 2022-07-10 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0105_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9fcc56b3-fa3a-4713-9810-73851ae1fc86'), editable=False, max_length=400, unique=True),
        ),
    ]
