# Generated by Django 3.2.12 on 2022-07-11 07:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0106_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('752781a8-34a9-4a25-9941-399706a0c9c8'), editable=False, max_length=400, unique=True),
        ),
    ]
