# Generated by Django 3.2.12 on 2022-07-19 05:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0107_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('43514fe5-bd5b-4f09-81c0-f4fa9cd2c79e'), editable=False, max_length=400, unique=True),
        ),
    ]
