# Generated by Django 3.2.12 on 2022-07-19 11:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0108_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('28b95192-0248-4bf1-ae90-dba6ddbd4df5'), editable=False, max_length=400, unique=True),
        ),
    ]
