# Generated by Django 3.2.12 on 2022-07-22 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0110_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('1f27a9d5-2a81-4773-98f9-5116a9f47ce7'), editable=False, max_length=400, unique=True),
        ),
    ]
