# Generated by Django 3.2.12 on 2022-07-23 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0111_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3cd120b3-f105-4847-a4dd-9c819137830f'), editable=False, max_length=400, unique=True),
        ),
    ]
