# Generated by Django 3.2.12 on 2022-07-23 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0112_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('b70e4ade-1075-4609-8647-7935be0fc8f1'), editable=False, max_length=400, unique=True),
        ),
    ]
