# Generated by Django 3.2.12 on 2022-07-23 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0113_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('23dff8ae-94b7-40a8-a801-88342629a6e8'), editable=False, max_length=400, unique=True),
        ),
    ]
