# Generated by Django 3.2.12 on 2022-07-24 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0115_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('8a76c417-04f6-4877-b551-c30bbad9ff0b'), editable=False, max_length=400, unique=True),
        ),
    ]
