# Generated by Django 3.2.12 on 2022-07-28 03:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0116_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('254e7092-5c4d-42bc-b971-52a671b0ee49'), editable=False, max_length=400, unique=True),
        ),
    ]
