# Generated by Django 3.2.12 on 2022-07-28 06:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0117_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9676d025-265c-49a9-83cf-f4baf239b6eb'), editable=False, max_length=400, unique=True),
        ),
    ]
