# Generated by Django 3.2.12 on 2022-07-30 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0118_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('aeffd3f8-d3e6-48d9-8bc4-d114f153296f'), editable=False, max_length=400, unique=True),
        ),
    ]
