# Generated by Django 3.2.12 on 2022-08-04 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0119_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3947e992-8229-49db-aed4-390a423833f8'), editable=False, max_length=400, unique=True),
        ),
    ]
