# Generated by Django 3.2.12 on 2022-08-04 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0120_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('cda0ac97-1de4-4034-9ebf-92d7b4a9d355'), editable=False, max_length=400, unique=True),
        ),
    ]
