# Generated by Django 3.2.12 on 2022-08-04 10:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0121_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('8b29e7f5-c9fa-44c9-8a4e-2a1d861c001b'), editable=False, max_length=400, unique=True),
        ),
    ]
