# Generated by Django 3.2.12 on 2022-08-05 11:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0122_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('03a3e0b6-f24e-407d-a6b5-d93dd1479378'), editable=False, max_length=400, unique=True),
        ),
    ]
