# Generated by Django 3.2.12 on 2022-08-05 11:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0123_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('76a14640-6f87-40b4-bbe2-9bbca2ccc538'), editable=False, max_length=400, unique=True),
        ),
    ]
