# Generated by Django 3.2.12 on 2022-08-06 11:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0124_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('560f4ba6-587c-4a0c-8bb1-fcd75399838e'), editable=False, max_length=400, unique=True),
        ),
    ]
