# Generated by Django 3.2.12 on 2022-08-07 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0126_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('b9b47963-8235-4a06-ac0e-81aa9373ea0f'), editable=False, max_length=400, unique=True),
        ),
    ]
