# Generated by Django 3.2.12 on 2022-08-07 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0127_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6df8fa2d-3145-4d96-b66b-1558de0b736d'), editable=False, max_length=400, unique=True),
        ),
    ]
