# Generated by Django 4.1 on 2022-08-07 15:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0128_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('dc52f324-5584-40f3-861c-7c556e29efd5'), editable=False, max_length=400, unique=True),
        ),
    ]
