# Generated by Django 4.1 on 2022-08-08 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0130_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('1a0e42cf-14d6-415c-aa01-6331de6970fc'), editable=False, max_length=400, unique=True),
        ),
    ]
