# Generated by Django 4.1 on 2022-08-08 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0131_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a0f72204-6d45-4bea-9422-f281f1cf2bf9'), editable=False, max_length=400, unique=True),
        ),
    ]
