# Generated by Django 4.1 on 2022-08-11 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0132_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4b6751a3-27e6-4754-afad-d485c9a3dc4e'), editable=False, max_length=400, unique=True),
        ),
    ]
