# Generated by Django 4.1 on 2022-08-12 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0133_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('35b8509f-78cd-474d-824a-a70932fcfc92'), editable=False, max_length=400, unique=True),
        ),
    ]
