# Generated by Django 4.1 on 2022-08-12 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0134_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e2b48cff-68a5-49de-a601-243e0f33742d'), editable=False, max_length=400, unique=True),
        ),
    ]
