# Generated by Django 4.1 on 2022-08-13 04:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0136_alter_post_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default=0, upload_to='main_site/blog/thumbnail_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6ee02802-a8f5-42f5-9b78-5f17b423c611'), editable=False, max_length=400, unique=True),
        ),
    ]
