# Generated by Django 4.1 on 2022-08-13 05:41

from django.db import migrations, models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0139_blog_category_details_category_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_category_details',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3a86640c-4e49-4cbf-a682-f232e1f2a29f'), editable=False, max_length=400, unique=True),
        ),
    ]
