# Generated by Django 4.1 on 2022-08-13 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0140_alter_blog_category_details_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('f9dfb31c-1114-4401-9b80-8f0a409d087d'), editable=False, max_length=400, unique=True),
        ),
    ]
