# Generated by Django 4.1 on 2022-08-13 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0141_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9d867588-e59d-49a9-8a03-37b0b950543e'), editable=False, max_length=400, unique=True),
        ),
    ]
