# Generated by Django 4.1 on 2022-08-13 07:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0142_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('b524772e-3268-434b-8944-77c368270660'), editable=False, max_length=400, unique=True),
        ),
    ]
