# Generated by Django 4.1 on 2022-08-13 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0143_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('eb5a41d3-6c56-4208-851d-84187a33c03e'), editable=False, max_length=400, unique=True),
        ),
    ]
