# Generated by Django 4.1 on 2022-08-13 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0144_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('c5e57e91-701c-4f9e-bdfd-7c59553e60d4'), editable=False, max_length=400, unique=True),
        ),
    ]
