# Generated by Django 4.1 on 2022-08-13 08:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0146_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4aceefc0-aa75-4d0e-a5be-ca02feeca5ba'), editable=False, max_length=400, unique=True),
        ),
    ]
