# Generated by Django 4.1 on 2022-08-13 08:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0147_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('dc6212c2-7728-49e4-8a36-c1e121cf2273'), editable=False, max_length=400, unique=True),
        ),
    ]
