# Generated by Django 4.1 on 2022-08-15 12:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0148_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('f692dc6e-06e7-41ff-aaeb-14985f6a6627'), editable=False, max_length=400, unique=True),
        ),
    ]
