# Generated by Django 4.1 on 2022-08-15 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0149_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('51db5c9e-e03d-4b61-873c-519555d73021'), editable=False, max_length=400, unique=True),
        ),
    ]
