# Generated by Django 4.1 on 2022-08-15 12:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0150_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('67792523-3c53-42a5-b53f-0a0ad13fecfb'), editable=False, max_length=400, unique=True),
        ),
    ]
