# Generated by Django 4.1 on 2022-08-16 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0151_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('76b0a91f-a263-447d-a0d0-6c4ebebdde3d'), editable=False, max_length=400, unique=True),
        ),
    ]
