# Generated by Django 4.1 on 2022-08-16 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0152_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('d5f98a53-8324-4c8f-8faa-bee4d7046fc1'), editable=False, max_length=400, unique=True),
        ),
    ]
