# Generated by Django 4.1 on 2022-08-16 14:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0153_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('369cf7a4-702e-4b57-ad88-64b64a6c2a69'), editable=False, max_length=400, unique=True),
        ),
    ]
