# Generated by Django 4.1 on 2022-08-16 14:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0154_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('df172b32-7d01-4e68-8c35-86eb68076665'), editable=False, max_length=400, unique=True),
        ),
    ]
