# Generated by Django 4.1 on 2022-08-16 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0155_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('5f49679c-ee90-473c-975c-c0005eb9c904'), editable=False, max_length=400, unique=True),
        ),
    ]
