# Generated by Django 4.1 on 2022-08-16 16:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0160_alter_vendor_gallery_photo_id'),
        ('blogs', '0156_alter_post_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_category',
            name='vendor_category',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('cec09830-c4ac-4eaf-aa44-b32b5bcb5c0c'), editable=False, max_length=400, unique=True),
        ),
    ]
