# Generated by Django 4.1 on 2022-08-17 08:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_admin', '0161_alter_vendor_gallery_photo_id'),
        ('blogs', '0157_blog_category_vendor_category_alter_post_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='vendor_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_admin.vendor_categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('832c77ea-5e82-43b1-8626-fb827d11af1c'), editable=False, max_length=400, unique=True),
        ),
    ]
