# Generated by Django 4.1 on 2022-08-17 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0158_post_vendor_category_alter_post_blog_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vendor_category',
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('fea99845-7a6a-41a3-901e-f36c29c4e3dc'), editable=False, max_length=400, unique=True),
        ),
    ]
