# Generated by Django 4.1 on 2022-08-18 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0159_remove_post_vendor_category_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('74ed5627-896d-4d06-a44c-32f8c8fb0b19'), editable=False, max_length=400, unique=True),
        ),
    ]
