# Generated by Django 4.1 on 2022-08-18 14:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0160_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('65d2b18d-c7be-44c4-8dad-c24e8ad34c61'), editable=False, max_length=400, unique=True),
        ),
    ]
