# Generated by Django 4.1 on 2022-08-18 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0161_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('186e377a-a901-40d8-a51e-12366dc60ba5'), editable=False, max_length=400, unique=True),
        ),
    ]
