# Generated by Django 4.1 on 2022-08-19 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0162_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9c3518d6-ce64-4997-a9b8-29689944f102'), editable=False, max_length=400, unique=True),
        ),
    ]
