# Generated by Django 4.1 on 2022-08-19 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0163_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('1abd4ee1-85b2-4973-9fa3-edef933e1d79'), editable=False, max_length=400, unique=True),
        ),
    ]
