# Generated by Django 4.1 on 2022-08-19 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0164_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('fbace835-c127-47af-bd5e-6aeff6448742'), editable=False, max_length=400, unique=True),
        ),
    ]
