# Generated by Django 4.1 on 2022-08-19 16:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0165_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('0668a1c1-0639-43ae-9111-d9517f9f8fa7'), editable=False, max_length=400, unique=True),
        ),
    ]
