# Generated by Django 4.1 on 2022-08-19 17:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0166_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('e698f227-7107-4aa9-aef5-f1f9bbcaf125'), editable=False, max_length=400, unique=True),
        ),
    ]
