# Generated by Django 4.1 on 2022-08-21 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0167_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('54670b4c-4abf-4274-9e49-5b21013cf8db'), editable=False, max_length=400, unique=True),
        ),
    ]
