# Generated by Django 4.1 on 2022-08-21 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0168_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('53a4b41b-42cd-44c4-ab1b-c3e912587c95'), editable=False, max_length=400, unique=True),
        ),
    ]
