# Generated by Django 4.1 on 2022-08-22 06:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0170_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('bc63d893-0e29-4038-bc44-070dc7b11ba4'), editable=False, max_length=400, unique=True),
        ),
    ]
