# Generated by Django 4.1 on 2022-08-22 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0171_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a9372340-e93d-40fe-aa72-a48148580c27'), editable=False, max_length=400, unique=True),
        ),
    ]
