# Generated by Django 4.1 on 2022-08-24 15:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0173_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('83e957f2-1570-492a-bab6-835cfc78f2fa'), editable=False, max_length=400, unique=True),
        ),
    ]
