# Generated by Django 4.1 on 2022-08-24 15:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0174_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('cac8477d-ee55-4b6d-85a9-677f01fef4ea'), editable=False, max_length=400, unique=True),
        ),
    ]
