# Generated by Django 4.1 on 2022-08-24 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0175_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('ac58cc6e-6734-4b34-bb59-fb9fb981013e'), editable=False, max_length=400, unique=True),
        ),
    ]
