# Generated by Django 4.1 on 2022-08-24 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0176_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('95557cdf-2211-4624-a887-69b7b217cc4b'), editable=False, max_length=400, unique=True),
        ),
    ]
