# Generated by Django 4.1 on 2022-08-24 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0177_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3287381e-9def-4af0-b4bf-0be7756482f1'), editable=False, max_length=400, unique=True),
        ),
    ]
