# Generated by Django 4.1 on 2022-08-25 12:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0178_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('11e4a0ea-6d1a-4258-b833-83b7f551e820'), editable=False, max_length=400, unique=True),
        ),
    ]
