# Generated by Django 4.1 on 2022-08-31 05:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0179_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('1c0a78c4-371e-45ac-9680-7f8a34b76bc1'), editable=False, max_length=400, unique=True),
        ),
    ]
