# Generated by Django 4.1 on 2022-09-03 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0180_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('73754b1f-51ac-4e8c-ac28-f91cd5b1ca74'), editable=False, max_length=400, unique=True),
        ),
    ]
