# Generated by Django 4.1 on 2022-09-04 07:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0181_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3c59e217-d3e0-470a-b788-0bb040a3528b'), editable=False, max_length=400, unique=True),
        ),
    ]
