# Generated by Django 4.1 on 2022-09-04 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0182_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3f254f9c-7e09-4020-8c80-137dbd725132'), editable=False, max_length=400, unique=True),
        ),
    ]
