# Generated by Django 4.1 on 2022-09-06 15:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0183_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3decafaf-ae58-4f6e-ae60-b47676388ef5'), editable=False, max_length=400, unique=True),
        ),
    ]
