# Generated by Django 4.1 on 2022-09-06 15:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0184_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a1f99fe1-1341-492a-9848-5818dc275e2c'), editable=False, max_length=400, unique=True),
        ),
    ]
