# Generated by Django 4.1 on 2022-09-07 11:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0185_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('b65b4020-02f9-4b6f-a200-ae7fb82b8e71'), editable=False, max_length=400, unique=True),
        ),
    ]
