# Generated by Django 4.1 on 2022-09-13 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0187_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('144f9b36-a8b1-41b8-af6c-edfea734d1e1'), editable=False, max_length=400, unique=True),
        ),
    ]
