# Generated by Django 4.1 on 2022-09-15 08:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0188_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4392d0e6-70e7-4eb4-a2cb-0beacbd60447'), editable=False, max_length=400, unique=True),
        ),
    ]
