# Generated by Django 4.1 on 2022-09-15 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0189_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('430be304-7535-4be9-8b3b-e2a3d0a9d995'), editable=False, max_length=400, unique=True),
        ),
    ]
