# Generated by Django 4.1 on 2022-09-15 17:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0190_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('f083578f-5cbf-41d6-acd2-df2a76cc65e2'), editable=False, max_length=400, unique=True),
        ),
    ]
