# Generated by Django 4.1 on 2022-09-20 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0191_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('51213bd9-3dcb-47be-9300-9b95b8059f93'), editable=False, max_length=400, unique=True),
        ),
    ]
