# Generated by Django 4.1 on 2022-09-20 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0192_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('6a7bb631-97fb-4e6b-a847-2f2387bc0b1d'), editable=False, max_length=400, unique=True),
        ),
    ]
