# Generated by Django 4.1 on 2022-10-01 20:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0193_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('89f9d7c5-c9d6-4f2c-95dd-81f0064952bb'), editable=False, max_length=400, unique=True),
        ),
    ]
