# Generated by Django 4.1 on 2022-10-01 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0194_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('930514ac-8e39-4c21-a303-61a517e32c31'), editable=False, max_length=400, unique=True),
        ),
    ]
