# Generated by Django 4.1 on 2022-10-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0195_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('bbf65eff-2f08-418c-a5d9-00e8808844dc'), editable=False, max_length=400, unique=True),
        ),
    ]
