# Generated by Django 4.1 on 2022-10-04 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0197_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('71e86a4e-3e0c-4b04-b965-3171f3734a77'), editable=False, max_length=400, unique=True),
        ),
    ]
