# Generated by Django 4.1 on 2022-10-05 04:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0198_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9cd3c4ff-467e-43ec-a18a-d8628eb86364'), editable=False, max_length=400, unique=True),
        ),
    ]
