# Generated by Django 4.1 on 2022-10-05 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0199_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('75ac44dd-bb05-4d87-a00a-5eb02c66bcb2'), editable=False, max_length=400, unique=True),
        ),
    ]
