# Generated by Django 4.1 on 2022-10-05 11:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0201_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('c65903ad-37cc-4114-ae18-17a749413171'), editable=False, max_length=400, unique=True),
        ),
    ]
