# Generated by Django 4.1 on 2022-10-08 12:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0202_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('fabd240a-fb2c-42d8-966a-bb87921ae122'), editable=False, max_length=400, unique=True),
        ),
    ]
