# Generated by Django 4.1 on 2022-10-08 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0203_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('41948938-615d-4561-a77c-8a318adc7742'), editable=False, max_length=400, unique=True),
        ),
    ]
