# Generated by Django 4.1 on 2022-10-08 14:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0204_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('93461f33-b4b8-4348-ad98-f907e6606da0'), editable=False, max_length=400, unique=True),
        ),
    ]
