# Generated by Django 4.1 on 2022-10-08 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0205_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('82428d23-2f20-48be-ab86-ac0c7d6b1190'), editable=False, max_length=400, unique=True),
        ),
    ]
