# Generated by Django 4.1 on 2022-10-08 16:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0206_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('f23f2cbc-6fad-40b9-bd64-fb656baebfd3'), editable=False, max_length=400, unique=True),
        ),
    ]
