# Generated by Django 4.1 on 2022-10-10 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0207_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('7531d20f-a94c-4093-8e4c-63415d664952'), editable=False, max_length=400, unique=True),
        ),
    ]
