# Generated by Django 4.1 on 2022-10-12 17:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0210_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('5689f6c5-7305-49a0-8bf0-ad47ed3299aa'), editable=False, max_length=400, unique=True),
        ),
    ]
