# Generated by Django 4.1 on 2022-10-16 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0212_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_category_details',
            options={'verbose_name_plural': 'Blogs Category Details'},
        ),
        migrations.AlterModelOptions(
            name='blog_cms',
            options={'verbose_name_plural': 'Blog Header Management'},
        ),
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('67b8ccf8-9384-4baa-99f2-778d97fa9a53'), editable=False, max_length=400, unique=True),
        ),
    ]
