# Generated by Django 4.1 on 2022-10-17 13:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0214_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('dbf89fde-03c2-4507-9b98-7981895c2441'), editable=False, max_length=400, unique=True),
        ),
    ]
