# Generated by Django 4.1 on 2022-10-17 17:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0215_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('27463584-57ee-42ce-a3ea-e4a00220834c'), editable=False, max_length=400, unique=True),
        ),
    ]
