# Generated by Django 4.1 on 2022-10-18 20:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0216_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4ca07fc4-b2a4-42d7-a9cb-acf5e3abd940'), editable=False, max_length=400, unique=True),
        ),
    ]
