# Generated by Django 4.1 on 2022-10-19 10:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0217_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('bc609b68-060b-49cd-960d-2e3865cd5d8f'), editable=False, max_length=400, unique=True),
        ),
    ]
