# Generated by Django 4.1 on 2022-10-19 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0219_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('3ff323f2-8897-451e-b88c-2ee1fb30df68'), editable=False, max_length=400, unique=True),
        ),
    ]
