# Generated by Django 4.1 on 2022-10-19 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0220_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('cf0bf4bc-1fb0-4ee8-9b82-5f7b0753e382'), editable=False, max_length=400, unique=True),
        ),
    ]
