# Generated by Django 4.1 on 2022-10-22 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0221_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('9dbc67cb-0c39-49e5-a4b1-6a7fad88db11'), editable=False, max_length=400, unique=True),
        ),
    ]
