# Generated by Django 4.1 on 2022-10-28 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0222_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('4a7b2d6a-f478-4772-8752-2cb46bcfcf3f'), editable=False, max_length=400, unique=True),
        ),
    ]
