# Generated by Django 4.1 on 2022-12-08 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0223_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('74a41839-6595-45e2-8a7c-9aac25f884fa'), editable=False, max_length=400, unique=True),
        ),
    ]
