# Generated by Django 4.1 on 2022-12-08 04:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0224_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('a2cb666a-aeff-40c6-819b-5e869cd8278e'), editable=False, max_length=400, unique=True),
        ),
    ]
