# Generated by Django 4.1 on 2022-12-08 04:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0225_alter_post_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog_id',
            field=models.CharField(default=uuid.UUID('26d4ac7a-5265-4d70-9d16-5d8592b68737'), editable=False, max_length=400, unique=True),
        ),
    ]
